### ISSUE TITLE
Modify UI to support Agents at the top level

### ISSUE THREAD

**Issue by paschmann** [paschmann/rasa-ui#1]

**Comment by paschmann** [comment]
- Include support for entities, training and integration to be separated

**Comment by tmbo** [comment]
I think that sounds great! @PHLF is currently working on adding async support as well as agent support build on that. I think that will make adding this way easier :+1:

**Comment by pradeepmvn** [comment]
@paschmann I am planning to move Entities under Agents on the UI. That will leave Agents, Training, Settings and Insights as top level Menus on the left. Is that the intention on this enhancement?

**Comment by paschmann** [comment]
@pradeepmvn - Its up to you ...  After doing some thinking on it, if users want to share Entities, they would need to create them for each Agent, I am not sure if thats what they would want. Unless we have a requirement, maybe we should hold off?

**Comment by paschmann** [comment]
@pradeepmvn - PS. I just saw your branch for core integration which includes moving entities - that works!!! :) So please ignore my previous comment.

**Comment by pradeepmvn** [comment]
@paschmann  great 👍 .Yes it will be with core integration and it is needed for it. Will close this enhancement.
