### ISSUE TITLE
No Train button visible on Ubuntu 16.04

### ISSUE THREAD

**Issue by brianhodge** [paschmann/rasa-ui#10]
There is no button to Train, despite seeing it in screenshots of the UI (A green button).  The only error on install was with an "optional" dependency, fsevent.  Also, I cannot bypass the standards rasa /parse?q= call, per the instructions, as it merely says /parse and /api/parse are not valid.  I looked at the routes and I saw nothing for parse.  It is running on an AWS instance that is running many third party programs.  I am familiar with permissions, port forwarding, etc.

I think the button not showing is due to a series of console warnings related to font-awesome issues?

Image - [http://ai.kadho.cn/font-issues.jpg](http://ai.kadho.cn/font-issues.jpg)

Rasa port 5000 - Working well
RasaUI port 5001 - Can create agents,entities,intents, but cannot train and cannot use /parse?q= or /api/parse?q=

It would seem the documentation is out of date.

**Comment by paschmann** [comment]
@brianhodge - thanks for pointing this out - I believe the documentation is incorrect ...

Could you try port : 5001/api/v2/rasa/parse?q=

**Comment by brianhodge** [comment]
That fixed that particular issue!  Thank you!  Great job by the way, really nice looking app.

As for the green button not showing up in Training, is the button built from any of the failing font libs?  Like simple lines builds a green rect and slaps some text on top?

Thanks again.
My company is working on AI models and integration heavily in two countries and this request came across for RasaUI.  I am the Technical Director and really hoping to solve this ASAP to increase production speed.

bhodge@kadho.com
http://www.kadhosports.com
http://www.kadho.cn

**Comment by paschmann** [comment]
Hi @brianhodge - glad to hear it has been useful!

I dont believe it would be related to the font problem, *if* you are seeing other icons throughout the app. I think this is a bug. I will look into this and provide a response ASAP.

**Comment by brianhodge** [comment]
Thank you very much for your time!

**Comment by paschmann** [comment]
Hi @brianhodge - I can replicate this issue if there are no entities/entity variables and if there is no expression attached to a entity. I would suggest opening up the dev tools in the browser along with the console and see which errors you are getting.

**Comment by brianhodge** [comment]
Image of console 
[Console Error]("http://ai.kadho.cn/rasaui-error.jpg")

Are you saying our trained models have an issue, or that there is something in the RASAUI flow i neglected to add?  Please forgive me, I am just trying to get this up for the team with limited knowledge.  I am catching up.

Thanks!

-Brian

**Comment by akshaysm** [comment]
im not getting button font and response also has some problem. i will get response object but entities array is empty, intents has only two objects "name" and "text". 
("name" as "greet" and "text" as queries typed in text box)

**Comment by danazen** [comment]
I came across the same issue. Start Training button is visible only when atleast one entity is mapped to an expression for a given agent.
