### ISSUE TITLE
Error with password database

### ISSUE THREAD

**Issue by amigliora** [paschmann/rasa-ui#100]
I am having this issue and I can not go anywhere :(

Please help, this is the message on the screen:

Rasa NLU Connected
Using connection string from: package.json
Rasa NLU Server: http://localhost:5000

Postgres DB Connection Error: error: password authentication failed for user "postgres"
Using connection string from: package.json
Adding to Sockets List: []
Adding to Sockets List: ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"]
Rasa NLU Config Request -> http://localhost:5000/config

**Comment by pradeepmvn** [comment]
@amigliora This looks like a connection error in the to the database. Please validate the postgres connection string. Also, try the same information in pgadmin and see if it works.
