### ISSUE TITLE
Rasa NLU Training Request Error  - Unable to train

### ISSUE THREAD

**Issue by krisand** [paschmann/rasa-ui#103]
When you click on the 'Start Training' from the Rasa UI from the Training Module, I get this error.
Is anyone getting the same error with the latest version?

Rasa NLU Config Request -> http://rasa-nlu:5000/config
--
  | Rasa NLU Train Request -> http://rasa-nlu:5000/train?project=WeatherBot
  | { ip_address: '10.175.232.7',
  | query: '/api/v2/rasa/train?name=WeatherBot_20180816-200052&project=WeatherBot',
  | event_type: 'train',
  | event_data:
  | { project: 'WeatherBot',
  | agent: 'WeatherBot_20180816-200052',
  | data: { rasa_nlu_data: [Object] } } }
  | Error occured while training. Response Code : 400 Body{
  | "error": "The request must have exactly one content type"
  | }

**Comment by smapley** [comment]
同样的问题

**Comment by pradeepmvn** [comment]
@krisand Please try the latest Master and reopen another issue if it still exist.
