### ISSUE TITLE
Load existing model?

### ISSUE THREAD

**Issue by ctrado18** [paschmann/rasa-ui#106]
Hey,

How can I use RasaUI for an existing model and a webchat GUI wich sends a userID for each user? Is this already automatcially served with RasaUI when connected to the bot such that the conversation of users are logged?

**Comment by ctrado18** [comment]
Any help?

**Comment by pradeepmvn** [comment]
@ctrado18 Sorry for the delay., But yes, rasa-ui can leverage exising model on the nlu server. All you need to do it create Agent in rasa-ui with the same name and you can test from the right side panel.
