### ISSUE TITLE
Support for Rasa Core Interactive Learning?

### ISSUE THREAD

**Issue by crownpku** [paschmann/rasa-ui#109]
I'm wondering if this project will also support Rasa Core, especially the interactive learning part. Currently Rasa Core uses command line for such interactive learning, and a user-friendly UI for this will be really helpful and completes the whole chatbot pipeline.

**Comment by paschmann** [comment]
@crownpku - we need Rasa Core to support learning from their HTTP API's, then we could add support in Rasa UI.

**Comment by Depado** [comment]
That would be amazing ! :smile:

**Comment by ctrado18** [comment]
I would love that!

**Comment by JohannesTK** [comment]
+1

**Comment by ThejanW** [comment]
Is this supported now?

**Comment by pradeepmvn** [comment]
Looks like its enabled using http APIs.
https://github.com/RasaHQ/rasa_core/blob/master/rasa_core/training/interactive.py
To support this Rasa ui should support Core latest release (atlease 0.11) which added Action server component.

**Comment by Husamx** [comment]
any updates on this?

**Comment by kootenpv** [comment]
I'm also wondering if this is still scheduled

**Comment by Spenhouet** [comment]
This would be a good feature. Any update?
