### ISSUE TITLE
Creating new users/login

### ISSUE THREAD

**Issue by careless25** [paschmann/rasa-ui#111]
Is there some documentation about this?

Instead of just admin/admin, can I create more users with some restrictions?
Use case:
- We have several users who are only going to add data to our models and we dont want them accessing other parts of rasa UI (traning, rasa core, etc).

So is there access management built in? Is there any other documentation?

**Comment by pradeepmvn** [comment]
@careless25 We used Keyclock as our IAM tool for Authentication and enabled a customauthentication function internally.
Rasa-ui out of the bos doesnt have any access management functions.
