### ISSUE TITLE
hosting rasaui on aws instance

### ISSUE THREAD

**Issue by ajkl** [paschmann/rasa-ui#114]
I am trying to setup rasaui on an AWS instance and expose it through the external ip.
I changed the security inbound rules to add port 5000 (rasa_nlu) and port 5001 to be accessed externally (from my local ip for now). 
rasa_nlu works fine when i try `<external-ip>:5000` but rasaui does not come up with `<external-ip>:5001` . I tried it locally with `curl http://localhost:5001` and it seems to return fine. 

The ui server seems to be running ok
```
Rasa UI Server: http://localhost:5001

Express server listening on port 5001

Rasa Core Error: Error: connect ECONNREFUSED 127.0.0.1:5005
Using connection string from: package.json


Rasa NLU Connected
Using connection string from: package.json
Rasa NLU Server: http://localhost:5000


Postgres DB Connected
Using connection string from: package.json
Postgres Server: 127.0.0.1:5432
Database:rasaui
Schema:public
```

What am i missing here ?

**Comment by pradeepmvn** [comment]
@ajkl is this still an issue?
Iam pretty sure it has to do with firewall rules.
