### ISSUE TITLE
How to do Step 2 and 3 in installing steps on wiki

### ISSUE THREAD

**Issue by satishAarbor** [paschmann/rasa-ui#117]
Can you explain about the following quoted steps:

"Step 2. Update your package.json file to include the IP Addresses of your rasa server and the connection string of your postgres instance."

"Step 3. Optional: Update your web/src/app.js file to include the IP Addresses of your local middleware server (no need to change this if the front end and middleware server are running on the same instance)" @pradeepmvn @paschmann

**Comment by pradeepmvn** [comment]
@satishAarbor Rasa Nlu server should be running on a seperate container or port and you should use that URL in package.json.
Ignore Step 3. I will update the documentation.

**Comment by OmarDhouib95** [comment]
could you please tell me how to update and use that URL in package.json? How should package.json look like?
Thanks you @pradeepmvn
