### ISSUE TITLE
Can't pass entity_synonyms

### ISSUE THREAD

**Issue by Oceania2018** [paschmann/rasa-ui#118]
![image](https://user-images.githubusercontent.com/1705364/46499561-0d0a8980-c7e6-11e8-9557-47c5f602aeb5.png)
![image](https://user-images.githubusercontent.com/1705364/46499856-e9940e80-c7e6-11e8-88fd-1800ea67191e.png)

**Comment by pradeepmvn** [comment]
@Oceania2018 Synonyms should be defined in the rasa ui itself. The UI will create synonyms for each user utterence and put that in training dataset for you. entity_synoyms do the same thing but with in the rasa_nlu server itself. Her eis a screen shot where you define synonyms for an entity.


![image](https://user-images.githubusercontent.com/2213762/46693673-80424000-cbd8-11e8-80df-5269e2ff4671.png)
