### ISSUE TITLE
Ability to Trigger training from rasa-ui

### ISSUE THREAD

**Issue by pradeepmvn** [paschmann/rasa-ui#12]
Enhancement: Each Agent will have a button to start the training process. This will export the Agent configuration and post it to RASA server in its format. Then keep checking the status for configured polling interval.

If there is no active work on this enhancement, i will work on it.

**Comment by paschmann** [comment]
Hi @pradeepmvn - could you elaborate, currently you can do this from Rasa UI directly from the "Training" Screen? You select the agent and then press train. Thanks! Paul

**Comment by pradeepmvn** [comment]
@paschmann  True that the Buttons only appear when Entities exists for an Agent. I will follow from #10
