### ISSUE TITLE
Crashing server when making POST request to rasa core

### ISSUE THREAD

**Issue by timofarei** [paschmann/rasa-ui#122]
Hi there,

first of all: Thank you very much for this awesome UI project!:)

I successfully installed rasa-ui on my mac. Everything is working fine as long as I only connect to the NLU server. But as soon as I activate the Rasa Core component then the rasa-ui server crashes. I tried tracking down the error and found that in the **[core_router.js](https://github.com/paschmann/rasa-ui/blob/master/server/routes/mw_routes/core_router.js)** file the POST request to rasa core uses "/parse". However, the [documentation](https://rasa.com/docs/core/server/) of the new version (0.11.12) of rasa core states that "/query" or "/message" should be used instead.

I tried to change the code to use "/query" and I successfully receive the intent-response of the core and the server does not crash anymore but I run into new problems.

I'm fairly new to ChatBots, APIs, JavaScript etc. therefore I fear that I cannot solve these issues myself yet. I wanted to ask whether you will update the code to work with the up to date rasa stack or whether I should just use an older version of the rasa stack?

Kindly,
Timo

**Comment by timofarei** [comment]
Ok, i found the solution: just had to downgrade rasa-core to 0.8.1 and rasa-nlu to 0.10.6.
Now everything works nicely:)

**Comment by aryadegari** [comment]
I have the same issue. When I enable Rasa-core for a bot and then test it with a message, rasa ui crashes. here is error log
```rasa_ui_1        | Got to parse middleware
[{"agent_id":2,"agent_name":"Arash","endpoint_enabled":false,"endpoint_url":null,"basic_auth_username":null,"basic_auth_password":null,"rasa_core_enabled":true}]
rasa_ui_1        | Messages.createUserMessage
rasa_ui_1        | routeRequest
rasa_ui_1        | Rasa Core Parse Request -> http://rasa_core:5005/conversations/admin/parse
rasa_ui_1        | Create Initial cache for rasa Core Parse Request
rasa_ui_1        | Message created successfully!!!
rasa_ui_1        | After request:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
rasa_ui_1        | <title>404 Not Found</title>
rasa_ui_1        | <h1>Not Found</h1>
rasa_ui_1        | <p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
rasa_ui_1        | 
rasa_ui_1        | undefined:1
rasa_ui_1        | <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
rasa_ui_1        | ^
rasa_ui_1        | 
rasa_ui_1        | SyntaxError: Unexpected token < in JSON at position 0
rasa_ui_1        |     at JSON.parse (<anonymous>)
rasa_ui_1        |     at Request._callback (/opt/rasaui/server/routes/mw_routes/core_router.js:108:24)
rasa_ui_1        |     at Request.self.callback (/opt/rasaui/node_modules/request/request.js:185:22)
rasa_ui_1        |     at Request.emit (events.js:182:13)
rasa_ui_1        |     at Request.<anonymous> (/opt/rasaui/node_modules/request/request.js:1161:10)
rasa_ui_1        |     at Request.emit (events.js:182:13)
rasa_ui_1        |     at IncomingMessage.<anonymous> (/opt/rasaui/node_modules/request/request.js:1083:12)
rasa_ui_1        |     at Object.onceWrapper (events.js:273:13)
rasa_ui_1        |     at IncomingMessage.emit (events.js:187:15)
rasa_ui_1        |     at endReadableNT (_stream_readable.js:1094:12)
rasa_ui_1        |     at process._tickCallback (internal/process/next_tick.js:63:19)
rasa_ui_1        | npm ERR! code ELIFECYCLE
rasa_ui_1        | npm ERR! errno 1
rasa_ui_1        | npm ERR! RasaUI@2.3.2 start: `node server/server.js`
rasa_ui_1        | npm ERR! Exit status 1
rasa_ui_1        | npm ERR! 
rasa_ui_1        | npm ERR! Failed at the RasaUI@2.3.2 start script.
rasa_ui_1        | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
rasa_ui_1        | 
rasa_ui_1        | npm ERR! A complete log of this run can be found in:
rasa_ui_1        | npm ERR!     /home/rasaui/.npm/_logs/2019-01-08T15_01_59_590Z-debug.log
```
It is stated in [Migration Guide](https://rasa.com/docs/core/migrations/#http-server-endpoints) that `/parse` endpoint is removed in 0.11.0 version.

**Comment by bamania8** [comment]
> Ok, i found the solution: just had to downgrade rasa-core to 0.8.1 and rasa-nlu to 0.10.6.
> Now everything works nicely:)

Thanks for sharing this detail....so on after moving to mentioned version ....Do we need to do any other changes...??? Like the request url ...from /parse to /query or any thing else.
