### ISSUE TITLE
Failed at the fibers@2.0.2 install script.

### ISSUE THREAD

**Issue by duybvk** [paschmann/rasa-ui#123]
> fibers@2.0.2 install /root/rasaui/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory `/root/rasaui/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
cc1plus: error: unrecognized command line option "-std=gnu++1y"
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/root/rasaui/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 2.6.32-754.6.3.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /root/rasaui/node_modules/fibers
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by gitkarumuga** [comment]
I had the same exact issue in Windows10 and Followed the installation guide [here](https://github.com/nodejs/node-gyp). It seems that **node-gyp** is a pre-requisite, so try following OS specific steps and let me know if this helps.

**Comment by paschmann** [comment]
@duybvk - is this issue resolved? Any feedback on what worked? Thanks!

**Comment by KMseven** [comment]
Even I faced this error. I saw somewhere that it only works with node 4, 5 and 6. So I downgraded my node version to 6 and it worked for me

**Comment by rgstephens** [comment]
I also had to downgrade to node 6
