### ISSUE TITLE
How to connect a webchat to rasa UI?

### ISSUE THREAD

**Issue by ctrado18** [paschmann/rasa-ui#124]
I struggle to understand what I neeed to do to connect the Rasa Ui to a webchat like from scalableminds or the rasa-chat.

Do I have to put an agent for NLU and Core(!) manually with stories and actions inside the UI such that I can log messages?!

Would appreciate help @paschmann ! As I am no js dev I like to have a simple starting guide?

When you send a message from the scalableminds it looks like:

`http://localhost:5002/conversations/senderID/say?message=Hi`

I think rasa ui needs the typical rasa core chiffre with `conversations/default/parse`

Do I need to convert this then for passing to rasa ui?

**Comment by ctrado18** [comment]
@paschmann Sure. But but I am not sure. If I use this little code I can use whole functionality of rasa ui? ANd what about the different url names coming from the chat? Also, I tried it but I did not work. I added the model name and the key with post man. What do i have to do in rasa ui? 

Do I actually need a whole within rasa ui trained agent for suing as a middle-ware? Why can't I upload the trained model? I saw that I need to write story and actions manually?

**Comment by pradeepmvn** [comment]
@ctrado18 Models reside on the NLU server. Rasa Maintains a reference to NLU project as aAgent name. So yes, rasa-ui should have the same Agent name as Project name in NLU. And thats all you need to test it. Closing this for now, feel free to open a new one if you still have an issue.
