### ISSUE TITLE
Refactor Dockerfile and use docker-compose to load multi-components

### ISSUE THREAD

**Issue by elvay1** [paschmann/rasa-ui#125]
In order to reduce image size, and stick with Docker best practices (single purpose container), I propose to :

- remove postgres from the rasa-ui container
- Create a docker-compose file to quickly run local rasa stack + UI environment

Does it suits you?

**Comment by paschmann** [comment]
@elvay1 - yes, sounds great!

**Comment by elvay1** [comment]
done with PR #130
