### ISSUE TITLE
Use dedicated schema and configurable user  in postgres

### ISSUE THREAD

**Issue by elvay1** [paschmann/rasa-ui#127]
According to[ postgres documentation](https://www.postgresql.org/docs/current/ddl-schemas.html#DDL-SCHEMAS-PORTABILITY) the public schema should not be used. 
Also, as the postgres user can be defined in the postgresserver environment variable, it should also be configurable in the database creation script.

I propose to transform these hardcoded values to variables in the dbcreate and migration scripts so they could be valorized on script execution time

**Comment by paschmann** [comment]
Hi @elvay1 - good point, if you would like to make the change I would be happy to include it through a pull request. Thanks!
