### ISSUE TITLE
how to map entitiy to training phrase

### ISSUE THREAD

**Issue by praveenkumart** [paschmann/rasa-ui#128]
how to map entitiy to training phrase

**Comment by paschmann** [comment]
1.) Create Entity
2.) Create Expression
3.) Highlight the word in the expression
4.) Press "Link" button
5.) Select the corresponding entity

![image](https://user-images.githubusercontent.com/4396042/49750935-2adaeb80-fc7a-11e8-8a39-0af8b0350f92.png)
