### ISSUE TITLE
Import of agent fails silently (500) 

### ISSUE THREAD

**Issue by beevelop** [paschmann/rasa-ui#129]
Trying to import an existing agent, I received no response from the UI. The browser's debugger reveals a failed HTTP request (500):
```json
{"status": "error", "message": {}}
```

Unfortunately there are no logs printed out by the server. Neither Rasa Core nor Rasa NLU throw a respective exception. I assume the behaviour is isolated to the Rasa-UI api.

----

Rasa-NLU config:
```yaml
language: "en"
pipeline: "spacy_sklearn"
```

Payload to import:
```json
{
   "agent_name":"neo",
   "data":{
      "rasa_nlu_data":{
         "common_examples":[
            {
               "intent":"handshake",
               "text":"handshake"
            },
            {
               "intent":"handshake",
               "text":"handshake foobar"
            },
            {
               "intent":"hello",
               "text":"hello"
            },
            {
               "intent":"hello",
               "text":"hi"
            },
            {
               "intent":"hello",
               "text":"howdy"
            }
         ],
         "regex_features":[],
         "lookup_tables":[],
         "entity_synonyms":[]
      }
   }
}
```

**Comment by huberrom** [comment]
We had a similar issue in our project, and it was because rasa UI need the field entities in your common examples, even if it's empty : 
          ` {
               "intent":"handshake",
               "text":"handshake",
               "entities": []
            }`
