### ISSUE TITLE
Use chat console with Rasa core 12.0

### ISSUE THREAD

**Issue by huberrom** [paschmann/rasa-ui#132]
Hi,

I'm currently using Rasa ui but not as a proxy (by that I mean my chat is calling my rasa core and not the rasa ui first) and then I'm logging everything on rasa ui to use insight (and training in the future). All my nlu stuff are in rasa ui and I'm training it using rasa ui too.

I'm currently upgrading the rasa router so I can use the chatbot with the rasa core version 12.0 (but it'll work by calling the rasa core, getting the answer and then posting the response on the rasa console). Since my rasa core is already logging everything, I'll not log anything with rasa ui.

To respect the previous version, the router will check the version of the rasa core and then use the router for rasa core under 11.0 version or the new router.

I'll open a pull requests (but in WIP since I'm still working on it) so you can give me feedbacks on it.

Is it ok with you @paschmann ?

**Comment by huberrom** [comment]
@paschmann My PR is ready, please take a look when you have the time.

As I said, all the "old" code is in the class rasa_server_V10 and is updated with the latest version (at 22h37 14/12/18 french time GMT+1), I didn't change anything so it should work with the oldest version of rasa core but do not hesitate to try it yourself.

There is still some ameliorations needed such as displaying correctly the text and the button (not breaklines for the moment)

**Comment by huberrom** [comment]
Thank you for you answer, I'll come back to on monday if it's ok. But I'm pretty sure that for my project we can't use rasa-ui as an action server. Maybe we can find a solution.

**Comment by elvay1** [comment]
Hi @pradeepmvn, I like @huberrom solution as it allows asynchronous logging to Rasa-UI, and then it does not put Rasa-UI at the same availibility and risks levels as the rest of the rasa stack.
Any Thoughts?

**Comment by huberrom** [comment]
@pradeepmvn Quick question about the previous version of the core_router.
I set my PR as WIP because I wanted to use the model selected in the drop down list but I noticed that it's not possible to specify the model (or the project) using the /respond endpoint of rasa core.
Did you use a different endpoint ? Was it possible to specify the project and the model ? 
I saw that only utter_message and webhook were accepted, so maybe you didn't make a call to the rasa core itself ?

**Comment by pradeepmvn** [comment]
> I wanted to use the model selected in the drop down list but I noticed that it's not possible to specify the model (or the project) using the /respond endpoint of rasa core.

@huberrom Model in the drop down is only specific for Rasa NLU. Rasa core will just create one statefull network and there is no need to specify any model there. To be specific to a rasa NLU model, you need to provide it as env details for rasa core. So no need to make any code reference to the model in core_router.  Core container/process will have an argument for the model to be specified.  

https://rasa.com/docs/core/docker_walkthrough/#connecting-rasa-core-and-rasa-nlu

https://github.com/pradeepmvn/rasa_stack_quickstart/blob/master/weatherbot/rasa_core/data/rasa_server.py

> I saw that only utter_message and webhook were accepted
Yeah those were the only actions that can be configured from rasa-ui. With 0.12 v you can remove th restrictions as they will be part of the action server implementation.

**Comment by huberrom** [comment]
@pradeepmvn That what I understood after reading the doc, so for the moment, my core_router_v12 will call the core specified in the dockerfile. My PR is ready to be review if you want, I'll delete the WIP status
