### ISSUE TITLE
asyncawait not compatible with Node v11

### ISSUE THREAD

**Issue by beevelop** [paschmann/rasa-ui#135]
As of right now, the dependency `asyncawait` leads to issues with Node v11. The installation of `fibers` fails.

<details>
<summary>Stacktrace</summary>

<pre>
> fibers@2.0.2 install /[...]/rasaui/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:318:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
                object->SetAccessor(isolate->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter);
                ^~~~~~~~~~~~~~~~~~~
../src/fibers.cc:464:24: warning: 'Utf8Value' is deprecated: Use Isolate version [-Wdeprecated-declarations]
                                        String::Utf8Value stack(uni::Deref(that.isolate, fatal_stack));
                                                          ^
/[...]]/.node-gyp/11.3.0/include/node/v8.h:2991:5: note: 'Utf8Value' has been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version",
    ^
/[...]]/.node-gyp/11.3.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/fibers.cc:686:66: error: too few arguments to function call, expected at least 2, have 1
                                Script::Compile(uni::NewLatin1String(that.isolate, "void 0;"));
                                ~~~~~~~~~~~~~~~                                              ^
/[...]]/.node-gyp/11.3.0/include/node/v8.h:1359:3: note: 'Compile' declared here
  static V8_WARN_UNUSED_RESULT MaybeLocal<Script> Compile(
  ^
../src/fibers.cc:701:66: error: too few arguments to function call, single argument 'context' was not specified
                                                uni::Reset(that.isolate, fatal_stack, try_catch.StackTrace());
                                                                                      ~~~~~~~~~~~~~~~~~~~~ ^
/[...]]/.node-gyp/11.3.0/include/node/v8.h:8878:3: note: 'StackTrace' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> StackTrace(
  ^
/[...]]/.node-gyp/11.3.0/include/node/v8config.h:418:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
2 warnings and 2 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
</pre>
</details>

----

Referring to the documentation of `asyncawait`, the module might not be necessary anymore:
> This library has enabled async/await coding style in Node.js since 2014. But JavaScript now has native async/await. JS async/await was standardized as part of ES2017, and has been enabled by default in Node.js since v7.6.

The dependency is only used in `core_router.js` and works seamlessly with native async/await too. I have the changes locally and would like to check beforehand if a PR makes sense for that @paschmann?

**Comment by paschmann** [comment]
@beevelop - sounds good - would be happy to incorporate a PR once tested - thanks!

**Comment by pradeepmvn** [comment]
@beevelop With the latest updates, this dependency has been removed. Rasa ui used to proxy requests to rasa core. Due to the API endpoints changes on rasacore side, it no longer does that.
