### ISSUE TITLE
Rasa-ui new functionality 1 : Synonyms and regex

### ISSUE THREAD

**Issue by huberrom** [paschmann/rasa-ui#145]
Hi @paschmann , @pradeepmvn 

we are using your project as part of one our company project, and we add a lot of new features in it because of our client needs. I'll open an issue for each functionnality, but I'll only make one PR because it's too hard for us too split them. You can respond on each of them if you have questions or comments about the functionnality. You can also contact us at romain.huber@cacd2.fr and romain.dauvert@cacd2.fr (@elvay1). We are sorry for the PR which is, I think, way too large to be reviewed, we had constraints. 

The first functionnality is the integration of the synonyms and regex in import/export and training. We linked them to an agent and changed the UI to add synonyms and regex in the agent management screen (see the file).
We also changed how you export synonyms to fit with rasa (add them in the end of the file, instead of adding new training examples)
 

![regex_synonyms](https://user-images.githubusercontent.com/19253772/51900570-f4863680-23b5-11e9-87a4-c09b1abfcf30.png)

**Comment by paschmann** [comment]
Hi @elvay1 & @huberrom - perfect - thanks!

**Comment by pradeepmvn** [comment]
Awesome!! 
@paschmann I am updated enpoints in the new branch rasa_ui-v2. I will merge these changes there and release it to the branch.

**Comment by huberrom** [comment]
Those changes would have to be merged with the v2, since we are based on this branch btw

**Comment by pradeepmvn** [comment]
@huberrom makes sense. Can you update to head of v2 and send us a PR.

**Comment by huberrom** [comment]
Yep, I think we are going to do it tomorrow. We are just two commit behind the head, we'll merge before the PR
