### ISSUE TITLE
Rasa-ui new functionality 2 : Conversation history management

### ISSUE THREAD

**Issue by huberrom** [paschmann/rasa-ui#146]
@paschmann 
Following #145 

The second huge change we made is the management of the conversation history.
We added a way to review conversation history and set intents and entities from the user history.
See the attached files for more information.
Small bug in add entity, the pop up say "add intention" instead of "add entity" but I'll correct it before the PR.
When an intention or an entity is set, the sentences is added to the training.

![conversation_history](https://user-images.githubusercontent.com/19253772/51901306-a114e800-23b7-11e9-9764-020feca48d92.png)
![one_conversation](https://user-images.githubusercontent.com/19253772/51901308-a1ad7e80-23b7-11e9-928f-45be2e468da5.png)
![add_entity](https://user-images.githubusercontent.com/19253772/51901303-a07c5180-23b7-11e9-9077-de0197c6b2ea.png)
![add_intention](https://user-images.githubusercontent.com/19253772/51901305-a114e800-23b7-11e9-95c9-a264f1393b4f.png)

**Comment by harunkelesoglu** [comment]
I imported agent. Dont show conversation history. What can be reason.
<img width="1669" alt="screen shot 2019-02-24 at 10 13 10" src="https://user-images.githubusercontent.com/9349762/53296275-f5778000-381c-11e9-8501-cced82872505.png">

**Comment by huberrom** [comment]
Importing the agent is not enough to have the conversation history. You have to configure something to fill the message table in your DB.

We are currently using logstash + rabbit MQ to fill those table from our core. Once all the tables are correctly filled, you'll see the conversations
