### ISSUE TITLE
Error in input

### ISSUE THREAD

**Issue by destroyerg** [paschmann/rasa-ui#149]
Hi everyone,

I have deployed succesfully rasa core and rasa nlu (according to the terminal output everything is connected) But I am having a couple of issues.

- The first one is when I create an agent if I click in the gear icon, nothing happens
- I can't use the input thing, the first dropdown is empty and if I click on Go nothing happens

So for sure I have done something wrong, but what?

Best,

**Comment by pradeepmvn** [comment]
@destroyerg can you please show the console log. Also, there are a bunch of latest updates to the master. Please try that and let us know.

**Comment by ratan019** [comment]
Getting error when going to add the agent.
```
net::ERR_EMPTY_RESPONSE

angular.js:15018 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","data":{"agent_name":"tes"},"url":"/api/v2/agents","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwibmFtZSI6IlBvcnRhbCBBZG1pbmlzdHJhdG9yIiwiaWF0IjoxNTQ5ODg1OTEyfQ.TbuerYCJaR3mHRPXezdtMrSiI2MRtR1yWCs3uX0K_7E","Content-Type":"application/json;charset=utf-8"}},"statusText":"","xhrStatus":"error","resource":{"agent_name":"herer"}}
```
Tried with docker and code based installation.
Both are throwing same error.

**Comment by pradeepmvn** [comment]
@ratan019 where did you see this error message? Can you paste console log.

**Comment by ratan019** [comment]
![image](https://user-images.githubusercontent.com/45257327/52611989-ee13b680-2ead-11e9-8bfc-a0f432267cb7.PNG)

It was my console log only, when i'm clicking on save button to save new agent , this is showing on my console log.

**Comment by tkalog** [comment]
Same issue here..any updates?

**Comment by alienatorZ** [comment]
I am running into the same issue as well. Chrome and Firefox..

**Comment by pradeepmvn** [comment]
There is an Internal Server error above the angular error.Can you see if there any error message on the nodejs console or docker consle? I just tested the master with fresh install and it workes fine on mac.

**Comment by tkalog** [comment]
No errors for me in the docker (nlu) or nodejs console..
Here is the log from the nodejs console:
![image](https://user-images.githubusercontent.com/47557444/52698787-883e3200-2f74-11e9-8620-acabc57e1acd.png)

**Comment by sanjeethanspal** [comment]
@pradeepmvn I am also having same issue
![alt Problem ](https://i.imgur.com/JJJHvAz.png)

**Comment by pradeepmvn** [comment]
Can you please try to delete node modules folder and run npm install and see if there are any errors?

**Comment by tkalog** [comment]
I tried deleting the node modules. All packages were added successfully, but still doesn't work.

**Comment by sanjeethanspal** [comment]
@tkalog Can I see all the logs of both server and browsers.
Following things possible
Either your rasa core or nlu endpoints or both are not working.

**Comment by tkalog** [comment]
@sanjeethanspal  Server logs:
![image](https://user-images.githubusercontent.com/47557444/52844952-257ca000-3106-11e9-92e4-85a09593de24.png)
It seems that nlu and postgres are connected.

Errors when trying to add an agent - by clicking "Save":
![image](https://user-images.githubusercontent.com/47557444/52845034-5f4da680-3106-11e9-9613-7876784daaae.png)

Logs on server after clicking "Save":
![image](https://user-images.githubusercontent.com/47557444/52845080-77bdc100-3106-11e9-9213-2cb236076223.png)

**Comment by sanjeethanspal** [comment]
@tkalog I'm very sure after going through your logs that your Rasa Core endpoint is not running. 
You can see this error in your log

> Rasa Core Error: Error: ECONREFUSED 127.0.0.1:5002;

Please make sure your both endpoints of rasa core and nlu are up.
You can check that by doing 

curl http://localhost:5002 -> core
curl http://localhost:5000 -> nlu
You can read about bringing core endpoint up by using[ this link](https://rasa.com/docs/core/server/)

> --enable-api flag

**Comment by tkalog** [comment]
@sanjeethanspal  
I think the rasa core is not necessary for this step (adding an agent).
 Is this the case?

**Comment by ratan019** [comment]
can anyone tell me the step by step process to integrate rocket chat with rasa ?

**Comment by sairahul** [comment]
No error but agent addition is failing.  In fact there is no response from the server. I can see the request going from the browser but no response from the server.

**Comment by ratan019** [comment]
> No error but agent addition is failing. In fact there is no response from the server. I can see the request going from the browser but no response from the server.

there is some configuration problem.you can check the below link:
 
https://www.youtube.com/watch?v=vx8DhOipdyw&t=212s

it may be helpful for you.

**Comment by Spenhouet** [comment]
I had the exact same issue. Turned out the `rasaui` I created on the Postgresql database had only read and no write access. Apparently Rasa-UI doesn't throw any errors whatsoever.
