### ISSUE TITLE
UTF-8 Error When Training from Rasa UI

### ISSUE THREAD

**Issue by arni5na** [paschmann/rasa-ui#151]
I'm getting the following error when initiating training from Rasa UI:
`Rasa NLU Train Request -> http://localhost:5004/train?project=cl_iva_agent&model=cl_iva_agent_20190202-194301
{ ip_address: '::1',
  query:
   '/api/v2/rasa/train?name=cl_iva_agent_20190202-194301&project=cl_iva_agent',
  event_type: 'train',
  event_data:
   { project: 'cl_iva_agent',
     model: 'cl_iva_agent_20190202-194301',
     data: { rasa_nlu_data: [Object] } } }
Error occured while training. Response Code : 500 Body[object Object]`

From Rasa NLU Server, I got the following warning:
`WARNING  rasa_nlu.data_router  - [Failure instance: Traceback (failure with no frames): <class 'rasa_nlu.train.TrainingException'>: utf-8
2019-02-02 19:43:04+0800 [-] ]`

My rasaui DB looks like this:
`CREATE DATABASE rasaui
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;`

Not sure what's wrong. Any help will be very much appreciated...

**Comment by pradeepmvn** [comment]
@arni5na Please try the same with the latest master codebase.
