### ISSUE TITLE
Error seems some data is missing. ({"error":"Can not train an empty pipeline. Make sure to specify a proper pipeline in the configuration using the `pipeline` key.The `backend` configuration key is NOT supported anymore."})

### ISSUE THREAD

**Issue by harunkelesoglu** [paschmann/rasa-ui#153]
Hi,
i have a trained model.I have ran rasanluserver and rasacoreserver in background using nohup.My postgresql is running. Finally i   have executed below command:

` docker run -e "rasanluendpoint=http://myserveraddress:5000" -e "rasacoreendpoint=http://myserveraddress:5005" -e "postgresserver=postgres://login:password@serveraddress:5432/rasa" -e "rasanlufixedmodelname=nlu" -itd -p 5001:5001 rasa-ui  `

when I try to train, I get an error like the following:
![screen shot 2019-02-07 at 15 58 00](https://user-images.githubusercontent.com/9349762/52412964-4aaf5400-2af1-11e9-957d-d029298aaaa1.png)

**Comment by pradeepmvn** [comment]
@harunkelesoglu Rasa NLU donot have the option of default pipeline. You will need to configure it for training. Can you try "rasa-ui_v2" branch? It should have an option to provide pipeline configuration.

**Comment by pradeepmvn** [comment]
Branch has been merged.  Please try the Master.
