### ISSUE TITLE
Tags for Docker image

### ISSUE THREAD

**Issue by beevelop** [paschmann/rasa-ui#155]
I'd like to suggest to add Docker tags to the officially provided Docker image.

With the changes of `v2` there seem to be some incompatibilities with older versions of Rasa which might lead to broken environments. To simplify managing the versions, it would be awesome to keep the tags of the repository in sync with the Docker tags.

**Comment by pradeepmvn** [comment]
@beevelop Yes I think we should have that. @paschmann Can you update the builds to include tags too.

**Comment by beevelop** [comment]
@paschmann With the release of v3 this would be more usable than ever. 😬 There is no easy way to use an old version from Dockerhub.

**Comment by bastian1993** [comment]
Totally agree, this would help a lot!

**Comment by paschmann** [comment]
@beevelop - I agree, good idea. Any suggestion on how we should tag it?

**Comment by beevelop** [comment]
<img width="1108" alt="Screenshot 2019-09-03 at 14 57 21" src="https://user-images.githubusercontent.com/6891349/64175231-2e8f4d80-ce5b-11e9-9737-60b9f631cc21.png">
I most often used something like this configuration for automated builds on Dockerhub. This automatically "synchronizes" the tags and keeps your `latest` in sync with `master`.

**Comment by paschmann** [comment]
![image](https://user-images.githubusercontent.com/4396042/64193620-216a6280-ce4b-11e9-88d6-6dce550955cf.png)

**Comment by paschmann** [comment]
Added, I guess next time we tag a build it will get tagged on docker hub as well. Thanks for the suggestion @beevelop - will close for now.
