### ISSUE TITLE
The requested URL was not found on the server.

### ISSUE THREAD

**Issue by algteam** [paschmann/rasa-ui#156]
If I choose a nlu model trained with rasaui, the following will occur.
![_15501341515570](https://user-images.githubusercontent.com/41173624/52774571-780f7b00-3078-11e9-8a26-c5dce0cab419.png)

**Comment by pradeepmvn** [comment]
@algteam 404 error could be the URL for RASA Core is wrong. Rasa core url should be the rest input channel one. Similar to the below one
```
"rasacoreendpoint": "http://localhost:5002",
 "rasacorerequestpath": "/webhooks/rest/webhook",
```

**Comment by algteam** [comment]
@pradeepmvn How to solve it?

**Comment by algteam** [comment]
@pradeepmvn 
![image](https://user-images.githubusercontent.com/41173624/52842833-47dce080-313b-11e9-98a8-a0a08400c727.png)
If I click the Go button, the following will appear in the log.
![screenshot from 2019-02-15 15-46-40](https://user-images.githubusercontent.com/41173624/52842375-e1a38e00-3139-11e9-8d0d-c81a5883727c.png)

**Comment by algteam** [comment]
I changed rasacorerequestpath=/conversations/{id}/parse to rasacorerequestpath=/webhooks/rest/webhook in the Dockerfile, the problem is solved.
