### ISSUE TITLE
Internal Server Error 500 - Rasa UI not communicating with middleware API's

### ISSUE THREAD

**Issue by sanjeethanspal** [paschmann/rasa-ui#157]
#**OS:**	Ubuntu 18.04.1 LTS (bionic)
**node:** v8.9.4
**npm:** v5.6.0

I am trying to use the rasa-ui by cloning the repository, and doing the npm install. All the dependencies has been installed successfully. PostgresSql is also working fine and is up, have imported the database successfully. I have placed all the configuration information correctly inside the package.json.
But following errors are coming in the console, seems to be the Rasa-ui is not able to connect to middleware API's of its own.

**Internal Server Error 500**
![screenshot from 2019-02-14 18-07-58](https://user-images.githubusercontent.com/44922676/52787416-c5ddb080-3083-11e9-9e3c-2acfbda3adab.png)

**Console Logs of Browser**
![screenshot from 2019-02-14 18-08-19](https://user-images.githubusercontent.com/44922676/52787417-c5ddb080-3083-11e9-9130-160a7c016118.png)

**Console Logs of Server**
![screenshot from 2019-02-14 18-11-21](https://user-images.githubusercontent.com/44922676/52787481-f6254f00-3083-11e9-9adf-66a29bfbcf78.png)

@pradeepmvn Please do assist me regarding it, where should I look to resolve this issue?

**Comment by pradeepmvn** [comment]
@sanjeethanspal I have tested with your node version too. It worked on my mac. From your logs, It looks like the rasa ui is started on localhost:5001, but your Internal server address shows an ip address (157.XX.XXX) Ideally everything should be on the local host.
Are you running middle ware on a seperate server?

**Comment by sanjeethanspal** [comment]
@pradeepmvn - Yes  I am running up the rasa-ui on a server whose address is 157.xxx, also rasa core and nlu along with postgres are on the same server (means everything is on the same server having this ip). And I have tried removing the node_modules folder couple of times and installing again but I am not getting any error, all the dependencies are getting installed with any error.

**Comment by pradeepmvn** [comment]
@sanjeethanspal In chrome under the network tab can you see what response you are getting for middleware nlu "/status" call?

**Comment by sanjeethanspal** [comment]
@pradeepmvn I am getting internal server 500 error, also I have attached the screenshot of this in the issue (1st Image). Please check.

**Comment by pradeepmvn** [comment]
@sanjeethanspal Can you add console.log(err) statement at below line and see what nodejs error prints out?

https://github.com/paschmann/rasa-ui/blob/adcaf97cd8930261aec581b88be7c4f5ee80005d/server/routes/mw_routes/nlu_router.js#L21

**Comment by sanjeethanspal** [comment]
@pradeepmvn Actually I was running up a docker container of rasa-ui along with cloned repository on the server, due to which this problem came up because two things were running at the same time. Now most of our problems has been solved after killing the docker container but now the problem is with the rasa side server, rasa core endpoint is running but not of rasa nlu.

![screenshot from 2019-02-15 09-37-33](https://user-images.githubusercontent.com/44922676/52833955-58726400-3105-11e9-84af-f60548427b19.png)
.
I'm also able to see the logs now.
![screenshot from 2019-02-15 09-35-08](https://user-images.githubusercontent.com/44922676/52833883-06314300-3105-11e9-867d-a4e7cd1975fc.png)

**Comment by pradeepmvn** [comment]
@sanjeethanspal glad the other issues were solved.
for NLU., its a 404 which means the rasa-ui server is unable to find the host for nlu server. Can you do a ping to the rasa_nlu server hostname from core.

**Comment by sanjeethanspal** [comment]
@pradeepmvn Its on the same server. Only rasa core is up but the rasa nlu endpoint is not running. Do you know how to run the endpoint of rasa nlu ?

**Comment by pradeepmvn** [comment]
@sanjeethanspal You can use rasa_nlu docker and start it. Or install it with pip and start the nlu server.

**Comment by sanjeethanspal** [comment]
Thanks @pradeepmvn, Rasa-UI is working fine now. Thanks for the help.
