### ISSUE TITLE
npm bugs RasaUI

### ISSUE THREAD

**Issue by venky14** [paschmann/rasa-ui#16]
Not able to connect Postgres to nodeJS
Updated IP address for Rasa server
"config": {
    "rasaserver": "http://localhost:5000",
    "postgresConnectionString": "postgres://postgres:password@localhost:5432/rasaui"
  }

Error
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose config Skipping project config: C:\Users\ADMIN/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle RasaUI@0.2.0~prestart: RasaUI@0.2.0
7 silly lifecycle RasaUI@0.2.0~prestart: no script for prestart, continuing
8 info lifecycle RasaUI@0.2.0~start: RasaUI@0.2.0
9 verbose lifecycle RasaUI@0.2.0~start: unsafe-perm in lifecycle true
10 verbose lifecycle RasaUI@0.2.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\ADMIN\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Broadcom\Broadcom 802.11\Driver;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files\Broadcom\WHL\;C:\Program Files\Broadcom\WHL\syswow64;C:\Program Files\Broadcom\WHL\SysWow64\;C:\Program Files\Broadcom\WHL\SysWow64\syswow64;C:\Program Files (x86)\Intel\Services\IPT\;C:\Program Files (x86)\Common Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\Java\jdk1.7.0_79\bin;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\MinGW\bin;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Python27;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\PostgreSQL\9.6\bin;C:\Program Files\PostgreSQL\9.6\lib;C:\Users\ADMIN\Anaconda2;C:\Users\ADMIN\Anaconda2\Scripts;C:\Users\ADMIN\Anaconda2\Library\bin;C:\Users\ADMIN\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\ADMIN\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\ADMIN\AppData\Roaming\npm
11 verbose lifecycle RasaUI@0.2.0~start: CWD: C:\Users\ADMIN
12 silly lifecycle RasaUI@0.2.0~start: Args: [ '/d /s /c', 'node server/server.js' ]
13 silly lifecycle RasaUI@0.2.0~start: Returned: code: 1  signal: null
14 info lifecycle RasaUI@0.2.0~start: Failed to exec start script
15 verbose stack Error: RasaUI@0.2.0 start: `node server/server.js`
15 verbose stack Exit status 1
15 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
15 verbose stack     at emitTwo (events.js:106:13)
15 verbose stack     at EventEmitter.emit (events.js:191:7)
15 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
15 verbose stack     at emitTwo (events.js:106:13)
15 verbose stack     at ChildProcess.emit (events.js:191:7)
15 verbose stack     at maybeClose (internal/child_process.js:891:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
16 verbose pkgid RasaUI@0.2.0
17 verbose cwd C:\Users\ADMIN
18 error Windows_NT 10.0.15063
19 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
20 error node v6.11.2
21 error npm  v3.10.10
22 error code ELIFECYCLE
23 error RasaUI@0.2.0 start: `node server/server.js`
23 error Exit status 1
24 error Failed at the RasaUI@0.2.0 start script 'node server/server.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the RasaUI package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node server/server.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs RasaUI
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls RasaUI
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by paschmann** [comment]
@venky14 - we have added an initial DB and Rasa NLP check at startup - please reopen the issue if this is still a problem
