### ISSUE TITLE
Error seems some data is missing. ("{\n \"error\": \"[E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.\"\n}")

### ISSUE THREAD

**Issue by harunkelesoglu** [paschmann/rasa-ui#161]
I got the following error, when I tried to train.
![screen shot 2019-02-20 at 08 52 01](https://user-images.githubusercontent.com/9349762/53069435-15d9ce80-34ed-11e9-9480-d4e45e7fc368.png)
My config file for nlu:
language: en
pipeline:
- name: tokenizer_whitespace
- name: ner_crf
- name: ner_synonyms
- name: intent_featurizer_count_vectors
- name: intent_classifier_tensorflow_embedding
cors_origins: ["*"]

**Comment by harunkelesoglu** [comment]
I have solved. Error is spacy package because I did not install.
`    python -m spacy download en_core_web_md &&
     python -m spacy link en_core_web_md en    `
i'm using tensorflow embedding  for pipeline. I don^t understand what i need spacy for

**Comment by pradeepmvn** [comment]
@harunkelesoglu Thanks for mentioning.
