### ISSUE TITLE
Failing to make docker work

### ISSUE THREAD

**Issue by tobeorla** [paschmann/rasa-ui#167]
I'm new to docker thing and i tried to follow the instructions listed in `readme.md` but localhost:5001 does not load.
1.  `docker pull paschmann/rasa-ui`
2. `open http://localhost:5001 in chrome`

Doesn't load.

As it didn't work i also tried to:
1.  `git clone https://github.com/paschmann/rasaui.git
cd rasaui && npm install`
2. `open http://localhost:5001 in chrome`

This time the ui loads, but nothing else does. Throws: 
- ECONNREFUSED 127.0.0.1:5432
- ECONNREFUSED 127.0.0.1:5000
- ECONNREFUSED 127.0.0.1:5002

**Comment by danielbussade** [comment]
Hi,

Please ensure the prerequisites are fulfilled:

Rasa NLU - Version 0.14+
Rasa Core - Version 0.12+
PostgreSQL - Used for storing training data (entities, intents, synonyms, etc.)
Node.js/npm - Serves Rasa UI and acts as a middleware server for logging (to the PostgreSQL DB)

You have install the Postgre SQL Server that it will run in http://127.0.0.1:5432 and the Rasa NLU that it will run in http://127.0.0.1:5000 and finally Rasa Core that it will run in http://127.0.0.1:5002.

So after that you can run the command above;
