### ISSUE TITLE
Broken wiki link

### ISSUE THREAD

**Issue by tobeorla** [paschmann/rasa-ui#169]
In https://github.com/paschmann/rasa-ui/wiki/Rasa-UI-Install-Guide:
`wget https://raw.githubusercontent.com/paschmann/rasa-ui/master/resources/dbcreate.sql`

`wget https://raw.githubusercontent.com/paschmann/rasa-ui/master/resources/database/dbcreate.sql`

Also docker setup didn't work, i had to manually improt dbcreate.sql commenting GRANT lines as they made the import explode.

**Comment by beevelop** [comment]
Considering your GRANT issue: It is mentioned in the README, that you need to specify the postgres_user explicitly.
> Please specify the value of the postgres_user parameter with your Rasa Postgres User, using psql : 
```bash
psql -v postgres_user=<RASA_UI_DATABASE_USER> -h <POSTGRES_SERVER_URL> -U <POSTGRES_ADMIN_USER> -d <RASA_UI_DB> -a -f dbcreate.sql.
```

**Comment by tobeorla** [comment]
In docker setup you're not expected to be running sql commands, i mentioned it because it may help you debugging why setup is broken.

**Comment by beevelop** [comment]
The docker-compose definition does not automatically setup the DB. You need to run the command above or the Flyway migrations like described in the README: https://github.com/paschmann/rasa-ui#flyway-install

**Comment by parthsharma1996** [comment]
So what is the correct link to the `dbcreate.sql` file?

**Comment by beevelop** [comment]
You can find it in the repository over here: https://github.com/paschmann/rasa-ui/tree/master/resources/database

**Comment by parthsharma1996** [comment]
Are there any parameters to be changes in the `package.json` config for postgres? (sorry for piling on this thread. I am not sure if this deserves a new thread in itself)

I followed all the steps in the wiki but I am getting the error
```
2019-04-24 10:29:59.248|rasa-ui|info|Postgres DB Connection Error: error: role "rasaui" does not exist;
```
on `npm start`

The documentation seems to be inadequate.
