### ISSUE TITLE
Train API is getting called 6 times for every single train request from UI

### ISSUE THREAD

**Issue by danazen** [paschmann/rasa-ui#17]
I have initiated the training only once but there are 6 train requests being sent from UI. I have configured 3 intents with 5 utterances each. When I train this agent it's getting triggered 6 times when I checked the log. 
I am using "mitie" pipeline in config.json. 

I am using the default config.py file.
"name": None,
    "config": DEFAULT_CONFIG_LOCATION,
    "data": None,
    "emulate": None,
    "language": "en",
    "log_file": None,
    "log_level": 'INFO',
    "mitie_file": os.path.join("data", "total_word_feature_extractor.dat"),
    "spacy_model_name": None,
    "num_threads": 1,
    "max_training_processes": 1,
    "path": "models",
    "port": 5000,
    "server_model_dirs": None,
    "token": None,
    "cors_origins": [],
    "max_number_of_ngrams": 7,
    "pipeline": [],
    "response_log": "logs",
    "aws_endpoint_url": None,
    "duckling_dimensions": None,
    "ner_crf": {
        "BILOU_flag": True,
        "features": [
            ["low", "title", "upper", "pos", "pos2"],
            ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"],
            ["low", "title", "upper", "pos", "pos2"]],
        "max_iterations": 50,
        "L1_c": 1,
        "L2_c": 1e-3
    },
    "intent_classifier_sklearn": {
        "C": [1, 2, 5, 10, 20, 100],
        "kernel": "linear"
    }
}

**Comment by paschmann** [comment]
hi @danazen - could you confirm if this is still an issue? Thanks!
