### ISSUE TITLE
/parse ajax request explodes when returned intent is empty

### ISSUE THREAD

**Issue by tobeorla** [paschmann/rasa-ui#170]
When rasa returns a null intent, rasa-ui's `/parse` request explodes.
In https://github.com/paschmann/rasa-ui/blob/master/server/routes/mw_routes/nlu_router.js#L372
it's using `rasa_response.intent.name` without checking if intent is not null.

My workaround has been to add in 
https://github.com/paschmann/rasa-ui/blob/master/server/routes/mw_routes/nlu_router.js#L173

the following code:
```js
let output = JSON.parse(body);

if (output.intent == null) {
    output.intent = { name: "" };
    body = JSON.stringify(output);
}
```

It works, but i don't think this is a great solution, so i did not make a PR with the patch.

**Comment by pradeepmvn** [comment]
@tobeorla I remember facing similar issue. What were your scenario for getting a null intent back?

**Comment by tobeorla** [comment]
I don't know why does return it empty :(
 I:
1. Created a new agent
1. Created some entities
1. Created an intent
1. Set some phrases with entities inside that intent and a static response.
1. Forced model name to be always the same
1. Trained the model. 

It does identify the entities, but intent is always null.
I think it's related to yml/md/files not begin properly set. I expected to be able to do everything from UI, but seems i will have to manually edit them too.

**Comment by pradeepmvn** [comment]
@tobeorla how many intents do you have. Rasa nlu expects a min of 2 intents and 2 expressions per each intent for intent classification to create a model and classify.

**Comment by tobeorla** [comment]
Ops, only 1 , i didn't get any exception when training, it said success.
I will create another one + the expressions and come back once i got the results.

**Comment by tobeorla** [comment]
Yes, it works!
