### ISSUE TITLE
How to show existing agent data?

### ISSUE THREAD

**Issue by Spenhouet** [paschmann/rasa-ui#172]
After some time fiddling around I got everything to start up (nlu server, rasa run, postgresql and rasa ui).

Now I can write request into the right side menu and that works but I don't have an agent.
From other answers I did read that I need to create an agent with the same name as project. I did that. Opening the agent just shows all fields as empty. How to properly load everything?

My training data files:

```
/data_train
  - domain.yml
  - nlu_data.md
  - stories.md
```

I have two folders for the nlu and core training output:

nlu output:

```
/models
  /current
    /dialogue
      - domain.json
      - domain.yml
      - policy_metadata.json
      - ....
```

core output:

```
/projects
  /name
    /current
      - checkpoint
      - ....
      - training_data.json
```

**What do I need to do to load everything in Rasa UI?**

**Comment by pradeepmvn** [comment]
@Spenhouet currenly rasa-ui supports importing an agent only for nlu data in json format. All the other data mighy be scripted to insert into postgres directly.

**Comment by Spenhouet** [comment]
Oh wow. That wasn't clear to me by any means. I expected it to automatically import an save all nlu and core training data. The UI doesn't communicate in any way that this functionality is so heavily limited.
Thanks for the clarification but that makes that whole UI useless for us.
