### ISSUE TITLE
Training of Rasa Core through and getting combined result from core and nlu for the query

### ISSUE THREAD

**Issue by sanjeethanspal** [paschmann/rasa-ui#174]
Hello,

When I'm pressing the start training button, it is only training the NLU.  Does Rasa-UI supports the training of the rasa-core? If yes, then how can I train the Rasa Core using the Rasa-UI. I have checked the training even after enabling the Rasa Core in the settings of the agent but still only trains the NLU.

Another question is, how to get the slot values using Rasa UI from the Rasa Core, as we are only getting the response_text from the Rasa Server.

Thanks.

**Comment by JoshuaZe** [comment]
for the policy training part, even Rasa-Core did not provide a HTTP call for online training.
here is the issue raised from rasa-core: https://github.com/RasaHQ/rasa_core/issues/422

**Comment by pradeepmvn** [comment]
@sanjeethanspal Rasa ui can train Rasa NLU directly. There is a manual step to deploy rasa-core. All the instructions and files are provided on the training page. as @JoshuaZe mentioned, http api doesn't exist for rasa core.
Slot Value can be used in rasa core response text. 
`Text  (You can use {slot_name} to have that automatically filled with value from rasa core)`is that what you were asking? Ex: Hello {user_name}.

**Comment by sanjeethanspal** [comment]
@pradeepmvn yeah this is one of the question, but I am saying that rasa core they do have conversation and session tracker for storing values of the slots and on the rasa server one can get the value of all the slots at the end of conversation by using tracker. But through API can we somehow get all the values of the slots at the end of the conversation using Rasa API on the rasaui.

@JoshuaZe 

Thanks
