### ISSUE TITLE
 Is there a way to create a separate Rasa Core model for every bot that we create

### ISSUE THREAD

**Issue by wanteetGithub** [paschmann/rasa-ui#176]
For every agent that is created, a new Rasa NLU model is created, but not a Rasa Core model. So when we send some text, the intent is correctly interpreted but the response from the core does not take into account the slot values that were passed. Do we need to create a separate Rasa Core model for every bot that we create? We need the context for every agent. Also is there a way to get slot values from the Rasa core?
Please advise.

**Comment by pradeepmvn** [comment]
@wanteetGithub Rasa core doesn't have the concept of a agent/project. It is a stateful process with the domain and stories.So if you make a change to those files, you would have to re-train core and start server.
How are you running rasa core and nlu? Rasa core endpoints.yml file should mention the url to rasa_nlu to interpret message.
