### ISSUE TITLE
How to bind entity to an action?

### ISSUE THREAD

**Issue by michaelscof** [paschmann/rasa-ui#183]
![issue](https://user-images.githubusercontent.com/24660402/54972466-b706e980-4fb1-11e9-97ca-6e89283cc502.PNG)
I have defined a couple of intents and their corresponding actions. The introduce intent is mapped to a name entity. I want the bot to call me as "hey {name}". Not very sure how to do that?
I tried with curly braces but it simply shows as text

**Comment by michaelscof** [comment]
@paschmann @pradeepmvn Can you please help?

**Comment by pradeepmvn** [comment]
@michaelscof Are you using Rasa Core? In Rasa core utter action template can do this. You have to set the entities as slots in the stories and rasa core can populate slots in responses.
