### ISSUE TITLE
Failed to load model metadata

### ISSUE THREAD

**Issue by JoseZamora97** [paschmann/rasa-ui#184]
Hi i am trying to run rasaui from a docker. But when i use docker-compose up i am getting a few errors when rasa_core_1 needs to start. In a nutshell, the console tell me this: 
```
rasa_nlu.model.InvalidProjectError: Failed to load model metadata from '/app/current/nlu/metadata.json'. [Errno 2] No such file or directory: 'current/nlu/metadata.json'
```
I am new in rasa. Thanks!

**Comment by coderlxn** [comment]
As the user said:
> On the first launch, you have to add add your rasa configurations and training files in this filetree:

And you need to link Rasa NLU Services to you Rasa Core as it described [here](https://rasa.com/docs/core/server/#connecting-rasa-nlu).
In endpoints.yml
```
nlu:
    url: http://rasa_nlu:5000
```
