### ISSUE TITLE
When i am trying to train nlu getting below some data format issue.

### ISSUE THREAD

**Issue by digumjo** [paschmann/rasa-ui#189]
When i try to train from ui, adding some intents getting below error.
Done with Request
Error occured while training. Response Code : 500 Body{
  "error": "Unknown data format for file /tmp/tmp8d8tgert_training_data"
}
![ss](https://user-images.githubusercontent.com/24625768/56097566-c8d60f80-5f13-11e9-9498-caf9f983d851.JPG)

**Comment by co-learning-lounge** [comment]
Even I am facing same issue. How to resolve it?
