### ISSUE TITLE
Compatibility with Rasa NLU >= 0.14.0

### ISSUE THREAD

**Issue by schinazi** [paschmann/rasa-ui#191]
Hi,

In Rasa NLU version 0.14.0, released 2019-01-23, the /config endpoint was removed (see https://rasa.com/docs/nlu/changelog/#v0-14-0).

The Rasa UI project readme currently says that Rasa NLU version 0.14.0 is supported, but Rasa UI still attempts to make use of /config.  Rasa NLU returns 404s for the request.  I believe this is resulting in the Rasa UI "input" sidebar's model dropdown not being populated.

Is it actually the case that 0.14.0 and later is not currently supported?

Thank you for your work on this project!

Best,
Brian Schinazi

**Comment by joneriktalvio** [comment]
Yup. This is the case. /config endpoint has been removed and this is now an issue, since we can't load the current project data. At least for me. I'm on 0.14.6.

**Comment by paschmann** [comment]
Hi @schinazi and @joneriktalvio  - if you are still using the project I would suggest checking out the v3 branch.
