### ISSUE TITLE
JSON data in trained model return not found.

### ISSUE THREAD

**Issue by JoseZamora97** [paschmann/rasa-ui#192]
Hi, I am getting this when I try one trained model.

![image](https://user-images.githubusercontent.com/35663120/56745366-85cd3500-677a-11e9-8c90-e31be2061fef.png)

**Comment by ProgramadorDeValor** [comment]
Hi, 

By just looking at the error, it's seems that it's not finding your Rasa Core/Nlu. Just a few questions as check mark before going deep into the problem. 

Yours Rasa NLU and Core are proper running ? 
Did you registered them correclty into Rasa UI ? 
Are you able to call them outside RasaUI, through command line?

**Comment by JoseZamora97** [comment]
Hi, 
Yes, NLU and Core are proper running in port 5000 and 5005 respectively, I go to localhost:5000 and localhost:5005 and a messages like Hello from Rasa NLU  appears.
What do you mean with registered into Rasa UI? When Rasa UI starts it show me NLU connected , Core connected and Postgres connected 
![image](https://user-images.githubusercontent.com/35663120/60191189-3ebff680-9834-11e9-94a8-9a8b506ff4e1.png)
I dont know how to call them outside RasaUI. I have NLU, CORE and Postgres running in dockers and I deploy all througt docker-compose up call from console.

**Comment by JoseZamora97** [comment]
@ProgramadorDeValor  I really appreciate if you can guide me step by step I been searching for information about this but I don't know how to solve this. I don't understand English well and I think I am misunderstanding the README.md. Thank you so much.
