### ISSUE TITLE
syntax error in dbcreate.sql

### ISSUE THREAD

**Issue by Stolaine** [paschmann/rasa-ui#193]
I have downloaded the dbcreate.sql from [here](https://github.com/paschmann/rasa-ui/blob/master/resources/database/dbcreate.sql)

when i tried to run `\i dbcreate.sql` i am getting syntax errors

(rasa_ui) [postgres@Hydidc-VoiceBOT-Srv1 ~]$ psql
psql (9.2.24)
Type "help" for help.

postgres=# \c rasaui
You are now connected to database "rasaui" as user "postgres".
rasaui=# \i dbcreate.sql
psql:dbcreate.sql:1: ERROR:  syntax error at or near "NOT"
LINE 1: CREATE SCHEMA IF NOT EXISTS "rasa_ui";
                         ^
psql:dbcreate.sql:3: ERROR:  schema "rasa_ui" does not exist
psql:dbcreate.sql:5: ERROR:  syntax error at or near ":"
LINE 1: GRANT ALL ON SCHEMA "rasa_ui" TO :postgres_user;
                                         ^
psql:dbcreate.sql:6: ERROR:  schema "rasa_ui" does not exist
DO
SET
psql:dbcreate.sql:23: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:30: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:37: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:44: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:51: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:58: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:65: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:72: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:79: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:86: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:93: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:100: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:107: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:114: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:121: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:128: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:135: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:142: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:149: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:156: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:163: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:187: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:201: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:218: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:233: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:248: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:258: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:272: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:283: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:296: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:315: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:328: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:346: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:367: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:386: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:403: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:418: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:436: ERROR:  no schema has been selected to create in
psql:dbcreate.sql:443: ERROR:  relation "intents" does not exist
LINE 3: ...ts.agent_name, grouped_intents.grp_intent_count from intents
                                                                ^
psql:dbcreate.sql:450: ERROR:  relation "nlu_parse_log" does not exist
LINE 3: ...g."timestamp", 'MM/DD'::text)) as month_date from nlu_parse_...
                                                             ^
psql:dbcreate.sql:457: ERROR:  relation "nlu_parse_log" does not exist
LINE 3: ...g."timestamp", 'MM/DD'::text)) as month_date from nlu_parse_...
                                                             ^
psql:dbcreate.sql:462: ERROR:  relation "nlu_parse_log" does not exist
LINE 3: ..."timestamp", 'MM/YYYY'::text)) as month_year from nlu_parse_...
                                                             ^
psql:dbcreate.sql:469: ERROR:  relation "nlu_parse_log" does not exist
LINE 3: ...g."timestamp", 'MM/DD'::text)) as month_date from nlu_parse_...
                                                             ^
psql:dbcreate.sql:483: ERROR:  relation "parameters" does not exist
LINE 11: FROM parameters
              ^
psql:dbcreate.sql:488: ERROR:  relation "nlu_log" does not exist
LINE 3: FROM nlu_log
             ^
psql:dbcreate.sql:492: ERROR:  relation "nlu_log" does not exist
LINE 3: FROM nlu_log;
             ^
psql:dbcreate.sql:500: ERROR:  relation "entities" does not exist
LINE 4: FROM entities
             ^
psql:dbcreate.sql:508: ERROR:  relation "nlu_log" does not exist
LINE 4: FROM nlu_log
             ^
psql:dbcreate.sql:519: ERROR:  relation "messages" does not exist
LINE 6: FROM messages AS msg
             ^
psql:dbcreate.sql:535: ERROR:  relation "messages" does not exist
LINE 8: FROM messages AS msg
             ^
psql:dbcreate.sql:537: ERROR:  syntax error at or near ":"
LINE 1: ...ALL PRIVILEGES ON ALL TABLES IN SCHEMA rasa_ui TO :postgres_...
                                                             ^
psql:dbcreate.sql:538: ERROR:  syntax error at or near ":"
LINE 1: ... PRIVILEGES ON ALL SEQUENCES IN SCHEMA rasa_ui TO :postgres_...
                                                             ^
psql:dbcreate.sql:541: ERROR:  relation "response_type" does not exist
LINE 2: INSERT INTO response_type (response_type_text) VALUES ('DEFA...
                    ^
psql:dbcreate.sql:542: ERROR:  relation "settings" does not exist
LINE 1: INSERT INTO settings (setting_name,setting_value) VALUES ('r...
                    ^
rasaui=#

**Comment by fallik** [comment]
Hi @Stolaine,
I replaced all occurances of `:postgres_user` in the sql Script with the username of the database.
I followed [the install guide](https://github.com/paschmann/rasa-ui/wiki/Rasa-UI-Install-Guide). However, I am using Mac OS.

Hope it helps.

**Comment by Ansud** [comment]
You need to update PostgreSQL. Early versions do not support CREATE SCHEMA **IF NOT EXISTS** command
