### ISSUE TITLE
fortify often misused: file upload error

### ISSUE THREAD

**Issue by karthikdav** [paschmann/rasa-ui#194]
When the UI code was scanned through Fortify tool it reported often misused: file upload security issue where we are trying to upload the file for eg in Agent_import. This issue is raised for input = file.

**Comment by paschmann** [comment]
@karthikdav - please add context and more details - we would love to resolve this.

**Comment by Naveenkorkopp** [comment]
@karthikdav Is this issue resolved ? Please share the solution.
