### ISSUE TITLE
Unable to login using admin/admin

### ISSUE THREAD

**Issue by farankardame** [paschmann/rasa-ui#20]
Hi, 

I have setup RasaUI with the latest code but I am unable to login using the console. 

Am I missing something? 

Thanks

**Comment by pradeepmvn** [comment]
Most cases it would be issue with node modules on web. Did you run npm install from within web/src directory? Can you check if there are any errors on the browser console.

**Comment by farankardame** [comment]
I think it was the nginx server which was not letting me login. Using it directly on port 5001 works. 

Thanks
