### ISSUE TITLE
Any way to disable authentication

### ISSUE THREAD

**Issue by beevelop** [paschmann/rasa-ui#206]
We are currently evaluating some parts of Rasa-UI and are running it behind Traefik. Traefik already comes with the capability to add authentication. Therefore it would be interesting for us to add a mode that requires no authentication.

Does this make sense to you? If I wanted to implement that functionality on my own, which parts would require changes?

**Comment by paschmann** [comment]
Hi @beevelop - are you suggesting the login screen should be optional (where you type in admin/admin)?

**Comment by beevelop** [comment]
Pretty much. As we use a reverse proxy like Keycloak Gatekeeper in most of our cases, we don't necessarily need an authentication on the application level. Thus we could skip the authentication screen completely.

But this could also be interesting for evaluation / development use cases. It would be awesome, if we could switch this option though an ENV.
