### ISSUE TITLE
Training error 404

### ISSUE THREAD

**Issue by tpinju00** [paschmann/rasa-ui#207]
What should I do to fix this error?

|rasa-ui|info|Rasa NLU Train Request -> http://localhost:5001/model/train;
|rasa-ui|info|Error occured while training. Rasa Server Response Code : 404;

**Comment by paschmann** [comment]
Hi @tpinju00 - please could you update your code base to the latest and let me know if the error persists.

**Comment by tpinju00** [comment]
Solved
