### ISSUE TITLE
Downloading psql Schema error 404

### ISSUE THREAD

**Issue by ZihaoTan** [paschmann/rasa-ui#211]
404：Not Found

**Comment by paschmann** [comment]
@ZihaoTan - could you share where this link is?

**Comment by ZihaoTan** [comment]
`wget https://raw.githubusercontent.com/paschmann/rasa-ui/master/resources/dbcreate.sql
`

**Comment by paschmann** [comment]
Hello @ZihaoTan - I have updated the wiki page to show that this is no longer needed with V3 of Rasa UI. Thanks!

**Comment by roynasser** [comment]
Hi @paschmann ,

Its still not reflecting that in the wiki for me?
![image](https://user-images.githubusercontent.com/1218902/64362772-7d68ee80-cfe5-11e9-8be8-44b189d2b97b.png)

(also if I may hijack this for a qucik question - I dont see a docker-compose, was this removed on purpose?  I found some links/issue mentioning it but I get a 404 )

**Comment by paschmann** [comment]
Hi @roynasser - you are correct, I just updated the TOC's for the wiki which it now shows the install reference as deprecated.

Re: Docker Compose - yes, I removed this to simplify the repo, I will review the requirement again.

**Comment by roynasser** [comment]
Got it! thanks!  I can contribute a "minimalist" docker-compose for "quickstart" if you'd like...

**Comment by paschmann** [comment]
Sure - please create a new issue and pull request! Thanks!

**Comment by beevelop** [comment]
@roynasser This would be great 👍

**Comment by roynasser** [comment]
I had some trouble with Rasa-ui (cant seem to "pull" or import my rasa bot into rasa-ui) so I stopped looking into it for now (want to come back to it as soon as I have some time)... 

This is what I put together for basic testing... I'll fork and submit a PR soon, but if anyone wants it:

Below is the docker-compose.yml
`
version: '3.0'

services:
  rasa:
    image: rasa/rasa:latest-full
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "rasadata:/app"
    command:
    - run
    - --enable-api

  action_server:
    image: rasa/rasa-sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./rasa-app-data/actions:/app/actions"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

  rasa_ui:       
    build:
      context: rasa-ui
    networks: ['rasa-network']
    ports:
      - "5001:5001"
    depends_on:
      - "rasa"
    environment:
      rasa_endpoint: "http://rasa:5005"

networks: 
  rasa-network:

volumes: 
  rasadata:
    driver: local
    driver_opts:
      type: none
      device: $PWD/rasa-app-data
      o: bind
`

Run below to get it up...
# Getting started:
# docker run -ti -v $(pwd)/rasa-app-data:/app rasa/rasa:latest-full init --no-prompt
This will get "sample" data into rasa so it comes up without issue.

# docker-compose up
To get the stack up

**Comment by paschmann** [comment]
Added docker-compose file @roynasser - I modified it slightly to keep it simple. Thanks for your help!
