### ISSUE TITLE
Errors when running from docker

### ISSUE THREAD

**Issue by Asma-droid** [paschmann/rasa-ui#213]
Hi all,

I would like to run rasa-ui from docker. Unfortunately, i have the following error:

rasa is up-to-date
rasa_ui is up-to-date     
Attaching to rasa, rasa_ui
rasa_ui    | 172.18.0.3
rasa_ui    |
rasa_ui    | > RasaUI@2.5.1 start /opt/rasaui
rasa_ui    | > node server/server.js
rasa_ui    |
rasa_ui    | 2019-09-13 12:13:53.861|rasa-ui|info|Rasa UI Server: http://localhost:5001;
rasa_ui    | 2019-09-13 12:13:53.863|rasa-ui|info|;
rasa_ui    | 2019-09-13 12:13:53.881|rasa-ui|info|;
rasa_ui    | 2019-09-13 12:13:53.881|rasa-ui|info|Rasa NLU Error: Error: connect ECONNREFUSED 127.0.0.1:5000;
rasa_ui    | 2019-09-13 12:13:53.881|rasa-ui|info|Using connection string from: process.env.rasanluendpoint;
rasa_ui    | 2019-09-13 12:13:53.881|rasa-ui|info|;
rasa_ui    | 2019-09-13 12:13:53.882|rasa-ui|info|;
rasa_ui    | 2019-09-13 12:13:53.882|rasa-ui|info|Rasa Core Error: Error: connect ECONNREFUSED 127.0.0.1:5005;
rasa_ui    | 2019-09-13 12:13:53.882|rasa-ui|info|Using connection string from: process.env.rasacoreendpoint;
rasa_ui    | 2019-09-13 12:13:53.882|rasa-ui|info|;
rasa_ui    | 2019-09-13 12:13:53.884|rasa-ui|info|Postgres DB Connection Error: Error: connect ECONNREFUSED 127.0.0.1:5432;
rasa_ui    | 2019-09-13 12:13:53.884|rasa-ui|info|Using connection string from: process.env.postgresserver;
rasa       | No chat connector configured, falling back to the REST input channel. To connect your bot to another channel, read the docs here: https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels
rasa       | 2019-09-13 12:14:05 DEBUG    rasa.core.utils  - Available web server routes:
rasa       | /conversations/<conversation_id>/messages          POST                           add_message
rasa       | /conversations/<conversation_id>/tracker/events    POST                           append_events
rasa       | /webhooks/rest                                     GET                            custom_webhook_RestInput.health
rasa       | /webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
rasa       | /model/test/intents                                POST                           evaluate_intents
rasa       | /model/test/stories                                POST                           evaluate_stories
rasa       | /conversations/<conversation_id>/execute           POST                           execute_action
rasa       | /domain                                            GET                            get_domain
rasa       | /                                                  GET                            hello
rasa       | /model                                             PUT                            load_model
rasa       | /model/parse                                       POST                           parse
rasa       | /conversations/<conversation_id>/predict           POST                           predict
rasa       | /conversations/<conversation_id>/tracker/events    PUT                            replace_events
rasa       | /conversations/<conversation_id>/story             GET                            retrieve_story
rasa       | /conversations/<conversation_id>/tracker           GET                            retrieve_tracker
rasa       | /status                                            GET                            status
rasa       | /model/predict                                     POST                           tracker_predict
rasa       | /model                                             DELETE                         unload_model
rasa       | /version                                           GET                            version
rasa       | 2019-09-13 12:14:05 INFO     root  - Starting Rasa server on http://localhost:5005
rasa       | 2019-09-13 12:14:05 INFO     root  - Enabling coroutine debugging. Loop id 94690724123352.
rasa       | 2019-09-13 12:14:05 DEBUG    root  - Could not load interpreter from 'models'.
rasa       | 2019-09-13 12:14:05 DEBUG    rasa.core.tracker_store  - Connected to InMemoryTrackerStore.
rasa       | 2019-09-13 12:14:05 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
rasa       | 2019-09-13 12:14:06 WARNING  rasa.core.agent  - Could not load local model in 'models'
Gracefully stopping... (press Ctrl+C again to force)
Stopping rasa_ui ... done
Stopping rasa    ... done
PS C:\Users\trabe\OneDrive\Documents\Test-Chatbot\rasa-ui> docker-compose up
Starting rasa ... done
Starting rasa_ui ... done
Attaching to rasa, rasa_ui
rasa_ui    | 172.18.0.3
rasa_ui    | 
rasa_ui    | > RasaUI@2.5.1 start /opt/rasaui
rasa_ui    | > node server/server.js
rasa_ui    |
rasa_ui    | 2019-09-13 12:16:37.314|rasa-ui|info|Rasa UI Server: http://localhost:5001;
rasa_ui    | 2019-09-13 12:16:37.316|rasa-ui|info|;
rasa_ui    | 2019-09-13 12:16:37.333|rasa-ui|info|;
rasa_ui    | 2019-09-13 12:16:37.333|rasa-ui|info|Rasa NLU Error: Error: connect ECONNREFUSED 127.0.0.1:5000;
rasa_ui    | 2019-09-13 12:16:37.334|rasa-ui|info|Using connection string from: process.env.rasanluendpoint;
rasa_ui    | 2019-09-13 12:16:37.334|rasa-ui|info|;
rasa_ui    | 2019-09-13 12:16:37.334|rasa-ui|info|;
rasa_ui    | 2019-09-13 12:16:37.334|rasa-ui|info|Rasa Core Error: Error: connect ECONNREFUSED 127.0.0.1:5005;
rasa_ui    | 2019-09-13 12:16:37.335|rasa-ui|info|Using connection string from: process.env.rasacoreendpoint;
rasa_ui    | 2019-09-13 12:16:37.335|rasa-ui|info|;
rasa_ui    | 2019-09-13 12:16:37.336|rasa-ui|info|Postgres DB Connection Error: Error: connect ECONNREFUSED 127.0.0.1:5432;
rasa_ui    | 2019-09-13 12:16:37.337|rasa-ui|info|Using connection string from: process.env.postgresserver;
rasa       | No chat connector configured, falling back to the REST input channel. To connect your bot to another channel, read the docs here: https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels
rasa       | 2019-09-13 12:16:42 DEBUG    rasa.core.utils  - Available web server routes:
rasa       | /conversations/<conversation_id>/messages          POST                           add_message
rasa       | /conversations/<conversation_id>/tracker/events    POST                           append_events
rasa       | /webhooks/rest                                     GET                            custom_webhook_RestInput.health
rasa       | /webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
rasa       | /model/test/intents                                POST                           evaluate_intents
rasa       | /model/test/stories                                POST                           evaluate_stories
rasa       | /conversations/<conversation_id>/execute           POST                           execute_action
rasa       | /domain                                            GET                            get_domain
rasa       | /                                                  GET                            hello
rasa       | /model                                             PUT                            load_model
rasa       | /model/parse                                       POST                           parse
rasa       | /conversations/<conversation_id>/predict           POST                           predict
rasa       | /conversations/<conversation_id>/tracker/events    PUT                            replace_events
rasa       | /conversations/<conversation_id>/story             GET                            retrieve_story
rasa       | /conversations/<conversation_id>/tracker           GET                            retrieve_tracker
rasa       | /status                                            GET                            status
rasa       | /model/predict                                     POST                           tracker_predict
rasa       | /model/train                                       POST                           train
rasa       | /model                                             DELETE                         unload_model
rasa       | /version                                           GET                            version
rasa       | 2019-09-13 12:16:42 INFO     root  - Starting Rasa server on http://localhost:5005
rasa       | 2019-09-13 12:16:42 INFO     root  - Enabling coroutine debugging. Loop id 93964688647624.
rasa       | 2019-09-13 12:16:42 DEBUG    root  - Could not load interpreter from 'models'.
rasa       | 2019-09-13 12:16:42 DEBUG    rasa.core.tracker_store  - Connected to InMemoryTrackerStore.
rasa       | 2019-09-13 12:16:42 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
rasa       | 2019-09-13 12:16:42 WARNING  rasa.core.agent  - Could not load local model in 'models'

**Comment by paschmann** [comment]
Hi @Asma-droid - how did you download the docker-compose file? From the Rasa UI Github release or did you clone the repo? It looks like the Rasa UI image is outdated in the docker-compose. Is it possible you have a old local copy of the Rasa UI image which the compose command is reusing?

**Comment by Asma-droid** [comment]
Hi @paschmann- Yes i have downloded Rasa ui from Github release, i have changed the endpoint address to localhost and i have added the docker-compose file. Attachments the zip file
[rasa-ui.zip](https://github.com/paschmann/rasa-ui/files/3610099/rasa-ui.zip)

**Comment by paschmann** [comment]
@Asma-droid - where did you find that rasa-ui.zip file/path? I think that is what is outdate and incorrect.
