### ISSUE TITLE
No Tests?

### ISSUE THREAD

**Issue by Bots4You-Heimel** [paschmann/rasa-ui#218]
I really like the project and would consider contributing and using it professionally. But I would not consider contributing to something without tests, as I am no masochist and I don't want to spend my time clicking buttons.
Please reconsider, I'm willing to help out if you are willing to work professionally.

**Comment by paschmann** [comment]
@Bots4You-Heimel - thanks for the recommendation, I recently added tests for some of the server components. Would you be interested in contributing tests for the front end?

**Comment by Bots4You-Heimel** [comment]
Sure, I will do that. Can start with it the weekend after this. You can look forward to my merge request.
