### ISSUE TITLE
Using Rasa UI v3 as Middleware

### ISSUE THREAD

**Issue by mroyce1** [paschmann/rasa-ui#223]
Hi,

I am currently running a Rasa bot with [rasa-webchat](https://github.com/mrbot-ai/rasa-webchat) as frontend. I'd like to add Rasa UI as a middleware. Previously, there used to be an [article in the wiki about that](https://github.com/paschmann/rasa-ui/wiki/DEPRECATED:-Using-Rasa-UI-as-Middleware) which has however been deprectated with v3.

My question is: Is it still possible to use Rasa UI v3 as a middleware? And if yes, how to do it?
 I tried both with and without Docker, but didn't succeed.

Thanks in advance

**Comment by paschmann** [comment]
@mroyce1 - this should still be possible. I will update the wiki to show how it would work in v3.

**Comment by paschmann** [comment]
@mroyce1 - I have updated the Wiki, please let me know if this does not work or you find any issues! Thanks!
