### ISSUE TITLE
How rasa core calls nlu model from rasa ui

### ISSUE THREAD

**Issue by kdigumar** [paschmann/rasa-ui#225]
@pradeepmvn hi,
I have nlu model and rasa core enabled. But when I am giving expression related to action getting core response.
but when I am trying to give user expression which is trained as Rasa NLU, still rasa core response is returned. 
How can I differentiate core and nlu response

**Comment by paschmann** [comment]
@kdigumar - sorry to hear about the issue, could you elaborate or provide some logs in this regards. I am not sure I understand your issue correctly.

**Comment by kdigumar** [comment]
Sorry too, I have nlu and core running separate servers. In rasa-uiI have added intents and trained nlu. Now I added actions(utter_) and given stories in rasa ui, and downloaded files and ran rasa core and it successfully up.
With rasa-core disable I could see good response and conversation with intents, entities, webhook.
But after enabling rasa-core in rasa ui, I am seeing empty response.
When I am trying to call rasa core via postman keeping jet authorisation, still I see empty response.
Not sure what I missed, can u suggest

**Comment by paschmann** [comment]
@kdigumar - please add your db.sqlite file to this issue. (from the server/data folder).

**Comment by kdigumar** [comment]
hey this has been resolved. model was not exposed, created storage and exposed it worked.
