### ISSUE TITLE
Documentation or instructions?

### ISSUE THREAD

**Issue by samboustani** [paschmann/rasa-ui#235]
Is there a guide on how a new person can get started after installing?  What is created first, the model or the bot?  What do the different pages mean?  What do we do about errors when trying to communicate with RSA NLU?  The Wiki says to find "beta" in the branches, but there is only a "master" branch. Is the master v3?  What is the red server icon on the top right?  There is no tooltip or any help on the UI, so not sure what some of these fields mean (server path to model file?  what's a server path look like in that field?)

**Comment by bamwani** [comment]
@samboustani  Did you find any?
