### ISSUE TITLE
Manage multiple bots from a single UI/instance of Rasa UI

### ISSUE THREAD

**Issue by Beherasaptami** [paschmann/rasa-ui#236]
any suggestion like how it will help me to manage multiple bots  ....

**Comment by Beherasaptami** [comment]
hello @paschmann how can i run multiple bots at same time and i am facing some issue while initiating chat like bot is able to respond for only once any suggestions will be helpful on this 
Thanks

**Comment by paschmann** [comment]
Hi @Beherasaptami - you can manage and maintain data for multiple bots in Rasa UI. However, Rasa removed the "Projects" feature last year. This removed the ability to run multiple bots on the same Rasa instance. (Read more: https://forum.rasa.com/t/removing-projects-for-rasa-nlu-server/8962/24) - I have tried to make it as simple as possible to load/test various models from Rasa UI, but technically if you wanted both running simultaneously, you would need 2 Rasa backends, which Rasa UI does not currently support :(
