### ISSUE TITLE
Please provide a good example

### ISSUE THREAD

**Issue by vasilevich** [paschmann/rasa-ui#25]
Dear community,
I am just starting out with RASA in general, and thus I tried this tutorial:
https://core.rasa.ai/tutorial_basics.html#goal

I would like to implement the same example, or any other example for that matter inside your UI.

may anyone please provide a basic "agent" example so I can import it using the "import agent" upload button?

I fail to find or to understand what the word "agent" stands for, as I see in rasa-npl no such word is used
such as here:
https://core.rasa.ai/tutorial_basics.html#goal

I am sorry if this is not considered an issuse, but I think lack of proper examples or documentation, is definetly an issuse in any project.

thank you!

**Comment by pradeepmvn** [comment]
@vasilevich rasa-ui works as an administration and management interface for rasa_nlu. You can use any rasa_nlu example and import it. 

A sample Agent can be created from this tutorial https://nlu.rasa.ai/tutorial.html

This tutorial uses https://github.com/RasaHQ/rasa_nlu/blob/master/data/examples/rasa/demo-rasa.json as Agent configuration. This can directly be imported as an agent into rasa-ui and test it.

Also there is a install guide in the wiki to get started https://github.com/paschmann/rasa-ui/wiki/Rasa-UI-Install-Guide

Rasa-ui only supports rasa_nlu as of now. Rasa Core support is yet to be added. Hope this helps.
