### ISSUE TITLE
Integration with Rasa Core

### ISSUE THREAD

**Issue by pradeepmvn** [paschmann/rasa-ui#26]
Add additional support to model domain and stories for rasa core from rasa-ui. This enhancement will create new tables in Postgres and all the data related to core models will be persisted to it.

**Comment by pradeepmvn** [comment]
@paschmann  Did you get a chance to look at the core-integration branch? Since rasa-core doesn't offer a train endpoint, I might build a workaround using a wrapper. For now, I will just provide a way to download these files from UI. 
Any thoughts?

**Comment by valicraciun** [comment]
+1

**Comment by paschmann** [comment]
Thanks for the integration @pradeepmvn !!! Awesome! PS. I just pushed another change I have been working on to simplify installation/node packages.

**Comment by paschmann** [comment]
@pradeepmvn - I think we can close this issue for now and open any issues needed for the new integration
