### ISSUE TITLE
Unable to make https calls to webhook - error “SELF_SIGNED_CERT_IN_CHAIN”

### ISSUE THREAD

**Issue by CROptum** [paschmann/rasa-ui#27]
My webhook has https with a self signed cert. rasa –ui / node throws an error saying “SELF_SIGNED_CERT_IN_CHAIN”

**Comment by pradeepmvn** [comment]
@CROptum This is an issue with nodejs/ request module when using a self signed certificate. Please check your node version before doing this change. There is a feature in node js(above v7.3) to add additional ca certs to the classpath using attribute **NODE_EXTRA_CA_CERTS** . Some steps to help extract the CA certs from the browser

- Browse to you webhook url in any browser
- Click on the security icon to view the certificates
- Download the certificates for each CA (there might be root CA, intermediate CA and so on)
- Copy all the certificates to one file. Make sure you include -----BEGIN CERTIFICATE----- and -----END CERTIFICATE----- lines from each certificate
- Give the file to system variable “NODE_EXTRA_CA_CERTS”
 
 
Ex: Within unix like environments (you don’t have to include and quotes)
```
export NODE_EXTRA_CA_CERTS=/home/download/certs/all_ca_certs.pem
```

Hope this resolves your issue.

**Comment by pradeepmvn** [comment]
Closing this. Please open another if it still exists
