### ISSUE TITLE
How to fix {"success":false,"message":"No Authorization header."}

### ISSUE THREAD

**Issue by kurodenjiro** [paschmann/rasa-ui#28]
I try to get API but it render . how to fix it 
![untitled](https://user-images.githubusercontent.com/26534614/34887949-ec9b70ee-f7fa-11e7-8527-cf2f5d2b9baf.png)

**Comment by pradeepmvn** [comment]
@kurodenjiro rasa-ui requires authentication before serving any data. You could browse to rasa ui home page ( to / ) and at the prompt enter a username and password (admin/admin by default). This will create a JWT session and point back to the same URL to see data.

You could also get the JWT token from the browser and use it in external tools such as postman/sopaui to make rest requests. Please update the issue if this information gets it resolved.

**Comment by kurodenjiro** [comment]
thank you i will try

**Comment by shibei00** [comment]
I have tried to enter the username and password, but it doesn't work.
