### ISSUE TITLE
POST api/v2/rasa/parse error

### ISSUE THREAD

**Issue by kurodenjiro** [paschmann/rasa-ui#29]
I try to do test this but it got error . how could i fix it

![untitled](https://user-images.githubusercontent.com/26534614/34893690-f79ec106-f810-11e7-9dec-94b8ec1a281e.png)

**Comment by pradeepmvn** [comment]
@kurodenjiro there are 2 components within rasa-ui : Angular app and nodejs server. Are you running them on different servers?

**Comment by kurodenjiro** [comment]
Yes i was running them on different servers . i changed them on same server but it still error

**Comment by kurodenjiro** [comment]
![untitled](https://user-images.githubusercontent.com/26534614/35113778-434dcd7e-fcb5-11e7-887f-5be9288da46c.png)

**Comment by pradeepmvn** [comment]
@kurodenjiro did you train from rasa-ui ? I think there is no model created or selected before you fire the parse request. After training is done, you should see your model in the UI, select it and then fire the parse request.

**Comment by kurodenjiro** [comment]
i had trained but it got some error 
Failed to load resource: the server respomd with a status of 42601
![untitled](https://user-images.githubusercontent.com/26534614/35138291-78e1e98c-fd20-11e7-9ca0-ef160345acd4.png)

**Comment by pradeepmvn** [comment]
@kurodenjiro Can you try with latest master. There is a fix that @paschmann submitted for entities.

**Comment by kurodenjiro** [comment]
@pradeepmvn  thank you training was fixed but api/v2/rasa/parse error still error

**Comment by kurodenjiro** [comment]
Thank you . it run we should create something noitify INPUT if it doesnt have model

**Comment by pradeepmvn** [comment]
@kurodenjiro   Thanks for your feedback 👍 . I added validation while submitting query text. Hope this helps. 

Closing this issue for now.
