### ISSUE TITLE
Limit on training data size

### ISSUE THREAD

**Issue by careless25** [paschmann/rasa-ui#33]
There is a limit on the training data size when trying to upload an existing dataset. This makes it really hard for existing models to be imported over to rasa-ui. 

e.g.: 
```
{message: "request entity too large", expected: 154631, length: 154631, limit: 102400, type: "entity.too.large"}
```

**Comment by ogienma** [comment]
Yeah, it looks like there's a 100kb cap by default. What I did is open up `server/server.js` ([here](https://github.com/paschmann/rasa-ui/blob/723a6f59e8eda1ff62ca9efcbcff1a2a8ed4fd7e/server/server.js#L20)) and changed this line:

`app.use(bodyParser.json());`

To include a higher limit:

`
  app.use(bodyParser.json({
      limit: '3mb'
    }));
`

Just my quick hack - the original contributors might have a better way of handling this.

**Comment by paschmann** [comment]
@ogienma - issue should be resolved with latest commit.
