### ISSUE TITLE
 api/v2/rasa/parse 404 (Not Found) 

### ISSUE THREAD

**Issue by kurodenjiro** [paschmann/rasa-ui#34]
i just reupdate new version of rasa-ui but api/v2/rasa/parse 404 (Not Found)  . 
![untitled](https://user-images.githubusercontent.com/26534614/35403004-d418eb92-0230-11e8-8108-755d88427359.png)

**Comment by kurodenjiro** [comment]
![untitled](https://user-images.githubusercontent.com/26534614/35403637-ea63ec2e-0232-11e8-9292-ac7e69b56c62.png)

**Comment by kurodenjiro** [comment]
{"error" : "Exception caught !!"}

**Comment by pradeepmvn** [comment]
@kurodenjiro 404 from middleware is misleading. I will change that error code to 500.
Do you see any node server stack error?

**Comment by paschmann** [comment]
Hello @kurodenjiro - this issue is resolved in the latest commit. Please create an additional issue if this is not the case for you.

**Comment by algteam** [comment]
@kurodenjiro  Is your problem solved?
