### ISSUE TITLE
Setup Issues

### ISSUE THREAD

**Issue by macasas** [paschmann/rasa-ui#36]
Perhaps similar problems to #31 
But I am running on OS X 10.12 so wiki installation guide for ubuntu makes little sense
I have the UI open, logged in but New Agent Save does nothing.

I have imported dbcreate.sql into postgres, but I don't have a rasaui database listed
Reading careless25's notes, create database rasaui;
I think perhaps my import went straight into postgres default database.

It does not say anywhere in the instructions to import sql into rasaui database, but is this necessary?
Do I need a particular username password combination?

Some details would be useful regarding database and user requirements? Can anyone supply them?

**Comment by kurodenjiro** [comment]
are you checking postsql connect ? telnet you server port sql on ubuntu and check it

**Comment by macasas** [comment]
I am running everything locally, there is no ubuntu, just OS X as I mentioned.

Postgres comes installed with mac os x.
Rasa_nlu server is running

Can you clarify the postgres import? Do I need to have specific users, create a table beforehand called rasaui?

**Comment by macasas** [comment]
If I run pg_isready in my Terminal is says it is accepting connections, 127.0.0.1 is my setup in rasaui

Daves-MacBook-Air:rasaui dave$ pg_isready -d postgres
/tmp:5432 - accepting connections
Daves-MacBook-Air:rasaui dave$ pg_isready -h 127.0.0.1
127.0.0.1:5432 - accepting connections

**Comment by pradeepmvn** [comment]
@macasas installation wiki has steps to create db and how to run the scripts. Outside of it you wouldn't need any additional user or db setup.

> psql

> postgres=# create database rasaui;
postgres=# ALTER USER postgres PASSWORD 'xxxxxxxxxx';
postgres=# \c rasaui
rasaui=# \i dbcreate.sql
rasaui=# \q

Does this help?

**Comment by macasas** [comment]
postgres=# create database rasaui;
CREATE DATABASE
postgres=# ALTER USER postgres PASSWORD 'xxxxxxxxxx';
ALTER ROLE
postgres=# \c rasaui
**FATAL:  password authentication failed for user "postgres"
Previous connection kept**
postgres=#

**Comment by macasas** [comment]
Okay, had to logout
So now I have the sql imported into the right database i think.

**Comment by macasas** [comment]
restarted server
restarted nlu server

UI does the same thing. Click Save button and nothing

> node server/server.js log looks like this
Rasa NLU Version Request -> http://127.0.0.1:5001/version
settings.getSettings
Rasa NLU Status Request -> http://127.0.0.1:5001/status
settings.getSettings
settings.getSettings
Agent.createAgent
Agent.createAgent
Agent.createAgent
Agent.createAgent
Agent.createAgent
Agent.createAgent
Agent.createAgent
Agent.createAgent
Agent.createAgent

**Comment by macasas** [comment]
Any ideas as to why I am still not able to add a new agent, 
click Save
server logs
Agent.createAgent
Rasa NLU Status Request -> http://127.0.0.1:5001/status
Rasa NLU Config Request -> http://127.0.0.1:5001/config

My postgres database now has a user postgres with password xxxxxxxxxx
It now also has a rasaui database

Database and host IP are both accepting connections
Daves-MacBook-Air:server dave$ pg_isready -d rasaui
/tmp:5432 - accepting connections
Daves-MacBook-Air:server dave$ pg_isready -h 127.0.0.1
127.0.0.1:5432 - accepting connections

There are 40 entries in the database, as shown below

Daves-MacBook-Air:server dave$ psql -U postgres
Password for user postgres: 
psql (10.1)

postgres-# \d
                         List of relations
 Schema |                Name                |   Type   |  Owner   
--------+------------------------------------+----------+----------
 public | active_user_count_12_months        | view     | postgres
 public | active_user_count_30_days          | view     | postgres
 public | agentidgen                         | sequence | postgres
 public | agents                             | table    | postgres
 public | agents_agent_id_seq                | sequence | postgres
 public | avg_nlu_response_times_30_days     | view     | postgres
 public | avg_user_response_times_30_days    | view     | postgres
 public | entities                           | table    | postgres
 public | entities_entity_id_seq             | sequence | postgres
 public | entity_synonym_variants            | view     | postgres
 public | entityidgen                        | sequence | postgres
 public | expression_parameters              | view     | postgres
 public | expressionidgen                    | sequence | postgres
 public | expressions                        | table    | postgres
 public | expressions_expression_id_seq      | sequence | postgres
 public | intent_usage_by_day                | view     | postgres
 public | intent_usage_total                 | view     | postgres
 public | intentidgen                        | sequence | postgres
 public | intents                            | table    | postgres
 public | intents_intent_id_seq              | sequence | postgres
 public | intents_most_used                  | view     | postgres
 public | nlu_log                            | table    | postgres
 public | nlu_log_log_id_seq                 | sequence | postgres
 public | nlu_parse_log                      | table    | postgres
 public | parameteridgen                     | sequence | postgres
 public | parameters                         | table    | postgres
 public | parameters_parameter_id_seq        | sequence | postgres
 public | parse_log_parse_log_id_seq         | sequence | postgres
 public | request_usage_total                | view     | postgres
 public | response_type                      | table    | postgres
 public | response_type_response_type_id_seq | sequence | postgres
 public | responseidgen                      | sequence | postgres
 public | responses                          | table    | postgres
 public | responses_response_id_seq          | sequence | postgres
 public | settings                           | table    | postgres
 public | synonym_variant                    | table    | postgres
 public | synonym_variant_synonym_id_seq     | sequence | postgres
 public | synonyms                           | table    | postgres
 public | synonyms_synonym_id_seq            | sequence | postgres
 public | unique_intent_entities             | view     | postgres
(40 rows)

**Comment by pradeepmvn** [comment]
@macasas can you check if there is any error in browser console? The DB has all the entities. Either DB connection issues, which should appear in nodejs console, or server issues which should appear in browser console.

**Comment by paschmann** [comment]
Hello @macasas - is this still an open issue?

**Comment by karthikveeramani** [comment]
This is still an open issue for me and I can't get the agent name to save on mac os :(

**Comment by macasas** [comment]
Sorry, this has never worked so I do not use it.

**Comment by pradeepmvn** [comment]
@macasas @karthikveeramani 
Can you create another issue with your specific problem? Is it a setup or agent creation problem with any log file will help.

**Comment by sameerg07** [comment]
Even I am running with the same issue. @macasas @karthikveeramani . Any help will be appreciated
