### ISSUE TITLE
Error occured while training agent: test Message: 401-"{\"success\":false,\"message\":\"No Authorization header.\"}"

### ISSUE THREAD

**Issue by JediRhymeTrix** [paschmann/rasa-ui#38]
Happens while trying to train an agent.

**Comment by pradeepmvn** [comment]
@JediRhymeTrix 

Rasa ui operates with a JWT token which contains logged in user and details. This should be part of the request authorization header. All of this is already part of UI and you shouldn't have to do anything in addition.

Are you using latest Master? And is this from UI after creating an agent?

**Comment by arunkumarry** [comment]
Getting the issue when trying to train the agent.

**Comment by paschmann** [comment]
@JediRhymeTrix & @arunkumarry - we have made multiple fixes/updates. Please could you retest and reopen this issue if it still persists. I have also updated the wiki to include some details on using RASA Ui as a middleware. [https://github.com/paschmann/rasa-ui/wiki/Using-Rasa-UI-as-Middleware](url)
