### ISSUE TITLE
Connection errors are not output in the terminal

### ISSUE THREAD

**Issue by saikojosh** [paschmann/rasa-ui#39]
Errors connecting to PostgreSQL and Rasa Core are swallowed and do not get output in the terminal. This makes debugging issues with the setup unnecessarily painful.

Consider adding appropriate error output.

**Comment by paschmann** [comment]
This is fixed in the latest commit - when the UI starts, we check the connection to Postgres and NLP, I have also drafted support for Rasa Core when we add it.
