### ISSUE TITLE
Publish the UI on Docker Hub

### ISSUE THREAD

**Issue by saikojosh** [paschmann/rasa-ui#41]
I had to publish my own copy of the UI to Docker Hub. It would be nice if you had a pre-baked one, seeing as you have a Dockerfile already in the repo.

**Comment by paschmann** [comment]
Thanks @saikojosh - and good point - hoping to put a docker file together with both Rasa Core + NLP + UI.

**Comment by paschmann** [comment]
https://hub.docker.com/r/paschmann/rasa-ui/
