### ISSUE TITLE
I got some error about /api/v2/rasa/parse 404 (Not Found)

### ISSUE THREAD

**Issue by kurodenjiro** [paschmann/rasa-ui#45]
How can i fix it 
![untitled](https://user-images.githubusercontent.com/26534614/36904788-3ff67ca4-1e64-11e8-9a68-efdcfc71e0cf.png)

![untitled](https://user-images.githubusercontent.com/26534614/36904599-a93d3672-1e63-11e8-917e-cafd41ffac6e.png)

**Comment by paschmann** [comment]
This issue should be resolved with the latest commit
