### ISSUE TITLE
No Authrization Header

### ISSUE THREAD

**Issue by jovenntann** [paschmann/rasa-ui#47]
I managed to run the RASA UI but we encountered problem when I clicked on training agent this error appeared. 

`Error occured while training. Response Code : 401 Body{"success":false,"message":"No Authorization header."}`

**Comment by paschmann** [comment]
Hi @jovenntann - did you use the latest commit?

**Comment by jovenntann** [comment]
Thanks . downloading latest commit resolve the issues.

**Comment by reza-ebrahimi** [comment]
I've testing with master branch and problem still there, I got following error:

`{"success":false,"message":"No Authorization header."}`

and so username and password `admin:admin` is not working.
