### ISSUE TITLE
Rasa Core is not enabled for this Agent

### ISSUE THREAD

**Issue by jovenntann** [paschmann/rasa-ui#49]
How to fix this? Thanks in advance

`Rasa Core is not enabled for this Agent`

**Comment by paschmann** [comment]
You would need to enable the Agent for "Rasa Core Integration". This is done by editing the agent on the agents screen. On a side note, I pushed a fix for a bug for not saving yesterday. So if you are using the latest commit you should be fine.

**Comment by jovenntann** [comment]
I can't seem enable the **Rasa Core Enablement**  there is no repsonse even on the logs.

**Comment by paschmann** [comment]
@jovenntann - please see latest commit for minor code change @pradeepmvn

**Comment by andresag** [comment]
I'm having the same issue. Can't find how to activate Rasa Core anywhere in the interface (agent screen?).

Did you get to solve it somehow, @jovenntann ?

@paschmann I cloned the repository last week, so I guess I'm running a pretty up to date version.

**Comment by tushar1328** [comment]
Can not edit the agent as the button does not give any response
