### ISSUE TITLE
Issue in starting rasa UI

### ISSUE THREAD

**Issue by ShrivastavAnurag** [paschmann/rasa-ui#50]
Hi,
I have setup the rasa-ui along with all pre-requisites. Whenever i try to start rasa-ui using "npm start" command I am getting following issues:

> RasaUI@0.2.0 start /var/rasa/rasaui
> node server/server.js

/var/rasa/rasaui/server/server.js:113
  console.log('Rasa UI Server: http://localhost:' + listener.address().port);
                                                                      ^

TypeError: Cannot read property 'port' of null
    at checkRasaUI (/var/rasa/rasaui/server/server.js:113:71)
    at Object.<anonymous> (/var/rasa/rasaui/server/server.js:107:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3

npm ERR! Linux 4.13.0-1011-gcp
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! RasaUI@0.2.0 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the RasaUI@0.2.0 start script 'node server/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the RasaUI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs RasaUI
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls RasaUI
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/rasa/rasaui/npm-debug.log

Please help me to resolve it.

**Comment by paschmann** [comment]
Hi - please comment this line out and see if it will start?

**Comment by pradeepmvn** [comment]
This should be solved with the updated code from master.

**Comment by memahesh** [comment]
HI,
can anyone tell me how to solve the above error ?
I cloned rasa ui just two days back. I followed all the steps. But I am getting the above error.
