### ISSUE TITLE
Postgres DB Connection Error: error: password authentication failed for user "postgres" Using connection string from: package.json

### ISSUE THREAD

**Issue by artiberde27** [paschmann/rasa-ui#52]
I am getting error Postgres DB Connection Error: error: password authentication failed for user "postgres"
Using connection string from: package.json when i run npm start

My postgres user password is "root".packages.json file mention

 "config": {
    "rasanluendpoint": "http://localhost:5000",
    "rasacoreendpoint": "http://localhost:5005",
    "coresecuritytoken": "",
    "nlusecuritytoken": "",
    "cacheagents": false,
    "jwtsecret": "th1s1sn0t0nlyths3cr3tbutth3m0st1mp0rtAntp13c30f1nf0rmAt10nf0rth1sAppl1cAt10n",
    "postgresserver": "postgres://root:rasaui@localhost:5432/rasaui"
  }

Thanks

**Comment by rafaelariad** [comment]
Hello @artiberde27 i think i can help,  maybe you have to change 
postgres://root:rasaui@localhost:5432/rasaui

For

postgres://root:rasaui@localhost:5432/root
 you could try that

**Comment by rafaelariad** [comment]
If 
user = root
And pass = root
And database = rasaui

postgres://root:root@localhost:5432/rasaui

**Comment by artiberde27** [comment]
Hi,
Thanks for your response
Below are my database details

user = postgres
And pass = root
And database = postgres


I changed my connection string to

postgres://root:postgres@localhost:5432/postgres

but i am still getting same error

**Comment by rafaelariad** [comment]
Try

postgres://postgres:root@localhost:5432/postgres

**Comment by pradeepmvn** [comment]
@rafaelariad  Thanks
@artiberde27 hopefully its resolved now. Closing the issue.

**Comment by devopsspider** [comment]
thanks 

> Try
> 
> postgres://postgres:root@localhost:5432/postgres

working
