### ISSUE TITLE
core integration files undefined with out an Entity/Slot definition

### ISSUE THREAD

**Issue by nkostop** [paschmann/rasa-ui#55]
Hello i am trying to create rasa core file from UI but the end up undefined and empty.
I have enabled Core integration support on my Agent.
I haven't started Rasa Core server.
Am i doing something wrong?
<img width="1226" alt="screen shot 2018-03-31 at 17 33 30" src="https://user-images.githubusercontent.com/15716129/38164222-ca8bc52a-3509-11e8-89d0-af0626fa99f7.png">
<img width="1225" alt="screen shot 2018-03-31 at 17 33 21" src="https://user-images.githubusercontent.com/15716129/38164226-cdb6484c-3509-11e8-9364-5707ce154f83.png">

**Comment by pradeepmvn** [comment]
@nkostop do you have any actions, stories defined? Rasacore server is required to test your model. Can you post any error messages from console or browser?

**Comment by nkostop** [comment]
Hello i have 
rasa_nlu.server running on behind and npm start the ui. 
Here is my agent settings
<img width="935" alt="screen shot 2018-03-31 at 18 27 22" src="https://user-images.githubusercontent.com/15716129/38164718-3480917a-3511-11e8-9d8e-72f2c13b73de.png">

Should i run rasa_core for these settings to by generated?
Thank you!

**Comment by nkostop** [comment]
Ok, i added some slots and now it works... maybe is a bug?

**Comment by kurodenjiro** [comment]
can you share this source

**Comment by karthikbalu** [comment]
I too have seen this issue #63

**Comment by pradeepmvn** [comment]
Can you please test with the latest master. I fixed the issue by removing the dependency on Entities.
