### ISSUE TITLE
Change Default Username and Password

### ISSUE THREAD

**Issue by carlosjosecazares** [paschmann/rasa-ui#56]
I want to start by saying that this is an awesome tool. Thank you for your time and effort in building/sharing Rasa UI. I have been working through an issue that I’ve been stuck on for some time. I would like to change the Rasa UI default login from admin/admin to something custom, but I’m having some trouble in doing so.

1. Is changing the username and password from admin/admin possible?
2. If so, where or how can it be changed?

Thank you in advance for your help.

**Comment by pradeepmvn** [comment]
@carlosjosecazares thanks for your feedback and kind words.Yes the default username and passwords can be changed here : [https://github.com/paschmann/rasa-ui/blob/a64493fcfe95debc05cef91c46db967d71847e0c/server/routes/auth.js#L7](url)

You can also modify that api to your custom authentication mechanism.

**Comment by carlosjosecazares** [comment]
Thank you very much. Found it!

**Comment by harunkelesoglu** [comment]
> https://github.com/paschmann/rasa-ui/blob/a64493fcfe95debc05cef91c46db967d71847e0c/server/routes/auth.js#L7

this url is not working

**Comment by sabatale** [comment]
@harunkelesoglu : How to change the credentials after install with default admin/amin when using dock-compose with UI + Rasa? It doesn't look like the UI allows you to do so and the credentials seem to be stored in global.admin-*?
