### ISSUE TITLE
user expressions not editable

### ISSUE THREAD

**Issue by shahzadahmadmalik** [paschmann/rasa-ui#57]
Great work! I think that if the User Expressions in "Intent Details" would be editable, it could help a lot in making a training file. For now, they are not editable. So, if I wanted a small change to the expression, I would have to first delete the previous one and write a new one.

I hope i was clear in defining the issue

Best Regards

**Comment by pradeepmvn** [comment]
@shahzadahmadmalik Thanks for your feedback. Will try to enhance Expressions section.
