### ISSUE TITLE
Rasa Core enablement and Save not working

### ISSUE THREAD

**Issue by anupam20sep** [paschmann/rasa-ui#61]
I have deployed RasaUI on server (UI and Postgresql being on same machine) and accessing it on my  local machine ( 0.0.0.0:5000/#!/agents ). When I create a new Agent and toggle Rasa core enablement switch and SAVE it, nothing happens (editagentinfo(agent) is not called I guess). Whereas when I am running the whole setup on my local machine and accesing through localhost:5000/#!/agents it works. I have tried on different browsers with no luck. Any idea what could be the problem?

**Comment by pradeepmvn** [comment]
@anupam20sep Any specific error messages that you see either on browser console or node server console? There is no additional configuration or setup needed for this mode of a deployment and technically it should work as is.

**Comment by anupam20sep** [comment]
closing this issue as it is been resolved. Just upgraded NPM and node. Thanks @pradeepmvn
