### ISSUE TITLE
<class 'rasa_nlu.train.TrainingException'>: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by ayashjorden** [paschmann/rasa-ui#62]
Hi,
I'm running RASA `NLU` and `CORE` as separate processes:
NLU = `python -mrasa_nlu.server  -c config_spacy.json --path models/nlu/`
CORE = `python run_rasa_core.py -d models/dialogue/ -u RasaNLUHttpInterpreter`

I've populated data into a rasaui Agent.
Went to the Training section and hit `Start Training`. this makes rasa_nlu throw an exception:
```
2018-04-26 23:01:45+0300 [-] 2018-04-26 23:01:45 ERROR    rasa_nlu.train - Failed to train project 'PROJECT_NAME'.
2018-04-26 23:01:45+0300 [-] Traceback (most recent call last):
2018-04-26 23:01:45+0300 [-]   File "/Users/jbar/venv/cubics-bot/lib/python3.6/site-packages/rasa_nlu/train.py", line 114, in do_train_in_worker
2018-04-26 23:01:45+0300 [-]     component_builder)
2018-04-26 23:01:45+0300 [-]   File "/Users/jbar/venv/cubics-bot/lib/python3.6/site-packages/rasa_nlu/train.py", line 136, in do_train
2018-04-26 23:01:45+0300 [-]     trainer = Trainer(cfg, component_builder)
2018-04-26 23:01:45+0300 [-]   File "/Users/jbar/venv/cubics-bot/lib/python3.6/site-packages/rasa_nlu/model.py", line 146, in __init__
2018-04-26 23:01:45+0300 [-]     components.validate_requirements(cfg.component_names)
2018-04-26 23:01:45+0300 [-]   File "/Users/jbar/venv/cubics-bot/lib/python3.6/site-packages/rasa_nlu/config.py", line 146, in component_names
2018-04-26 23:01:45+0300 [-]     return [c.get("name") for c in self.pipeline]
2018-04-26 23:01:45+0300 [-]   File "/Users/jbar/venv/cubics-bot/lib/python3.6/site-packages/rasa_nlu/config.py", line 146, in <listcomp>
2018-04-26 23:01:45+0300 [-]     return [c.get("name") for c in self.pipeline]
2018-04-26 23:01:45+0300 [-] AttributeError: 'str' object has no attribute 'get'
2018-04-26 23:01:45+0300 [-] 2018-04-26 23:01:45 WARNING  rasa_nlu.data_router - [Failure instance: Traceback (failure with no frames): <class 'rasa_nlu.train.TrainingException'>: 'str' object has no attribute 'get'
2018-04-26 23:01:45+0300 [-] ]
```

Rasa-NLU config:
```
{
  "project": "PROJECT_NAME",
  "pipeline": [
    "nlp_spacy",
    "tokenizer_spacy",
    "intent_entity_featurizer_regex",
    "intent_featurizer_spacy",
    "ner_crf",
    "ner_synonyms",
    "intent_classifier_sklearn",
    "ner_spacy"
  ],
  "path": "./models/nlu",
  "port": 5000,
  "data": "./data/PROJECT_NAME-small.json",
  "language": "en",
  "log_level": "DEBUG",
  "fixed_model_name": "MODEL_NAME_support"
}
```

Please advise,
Yarden

**Comment by pradeepmvn** [comment]
@ayashjorden This shows an issue with pipeline config for NLU Server. I remember getting this error for one of my JSON pipeline. Can you try converting the JSON config file to yml. Your config equvalent will be similar to one below and start the rasa nlu server with this config file

```
project: "PROJECT_NAME"
pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
- name: "ner_spacy"
path: "./models/nlu"
port: 5000
data: "./data/PROJECT_NAME-small.json"
language: "en"
log_level: "DEBUG"
fixed_model_name: "MODEL_NAME_support"
```

**Comment by tmbo** [comment]
All the parameters but `pipeline` and `language` should be passed as argument to the command line scripts, they are not read from the config anymore.

**Comment by ayashjorden** [comment]
@pradeepmvn, I tricked the config file ;)
This is my pipeline now:
```
  "pipeline": [
    { "name": "nlp_spacy" },
    { "name": "tokenizer_spacy" },
    { "name": "intent_entity_featurizer_regex" },
    { "name": "intent_featurizer_spacy" },
    { "name": "ner_crf" },
    { "name": "ner_synonyms" },
    { "name": "intent_classifier_sklearn" },
    { "name": "ner_spacy" }
  ],
```

@tmbo , can you please elaborate? is this best-practice or deprecation warning?

**Comment by pradeepmvn** [comment]
@ayashjorden I was looking thru the latest code for nlu and as @tmbo mentioned all the config perms except pipeline and language will be part of nlu server start command.

For ex: to start server with remote storage, 
`python -m rasa_nlu.server -c config.yml --path /app/projects --storage aws`

Docker equivelent command from nlu image.
`CMD ["start", "-c", "config.yml", "--path", "/app/projects", "--storage", "aws"]`

It can either be in json or yml format. Hopefully this helps. Closing this issue.

@tmbo Thanks much for your help.

**Comment by nadabou** [comment]
@sandy130794 were you able to solve this issue ? I am currently encountering the same error.
But my configuration file is different:
`
language: "en"

pipeline: "spacy_sklearn"
`

**Comment by skrmz** [comment]
I'm now using a newer version (0.15.0a1) but still running into the same problem:

start training:
`> curl -XPOST --header 'content-type: application/x-yml' --data-binary @../conf/small-training.yml localhost:5000/train?project=nlu&model=mainmodel`

server log:
```
2019-02-18 09:18:07+0000 [-]  Traceback (most recent call last):
rasa_1              | 2019-02-18 09:18:07+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/reflect.py", line 448, in safe_str
rasa_1              | 2019-02-18 09:18:07+0000 [-]     return str(o)
rasa_1              | 2019-02-18 09:18:07+0000 [-] TypeError: __str__ returned non-string (type int)
rasa_1              | 2019-02-18 09:18:07+0000 [-] >
rasa_1              | 2019-02-18 09:18:07+0000 [-] ]
rasa_1              | 2019-02-18 09:18:07+0000 [-] Unhandled Error
rasa_1              | 	Traceback (most recent call last):
rasa_1              | 	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
rasa_1              | 	    self._startRunCallbacks(fail)
rasa_1              | 	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
rasa_1              | 	    self._runCallbacks()
rasa_1              | 	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
rasa_1              | 	    current.result = callback(current.result, *args, **kw)
rasa_1              | 	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
rasa_1              | 	    _inlineCallbacks(r, g, status)
rasa_1              | 	--- <exception caught here> ---
rasa_1              | 	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
rasa_1              | 	    result = result.throwExceptionIntoGenerator(g)
rasa_1              | 	  File "/usr/local/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
rasa_1              | 	    return g.throw(self.type, self.value, self.tb)
rasa_1              | 	  File "/app/rasa_nlu/server.py", line 361, in train
rasa_1              | 	    returnValue(json_to_string({"error": "{}".format(e)}))
rasa_1              | 	builtins.TypeError: __str__ returned non-string (type int)
```
my pipeline conf is:
```
pipeline:
- name: "tokenizer_whitespace"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
  lowercase: true
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "_"
```

any ideas?

**Comment by digumjo** [comment]
HI All, when i am trying to deploy rasa- core getting this error can any one help.


File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
--
  | "__main__", mod_spec)
  | File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
  | exec(code, run_globals)
  | File "/data/rasa_server.py", line 28, in <module>
  | cmdline_args.cors)
  | File "/app/rasa_core/server.py", line 175, in create_app
  | if not agent.is_ready():
  | AttributeError: 'str' object has no attribute 'is_ready'

my server.py


import logging
import os
from rasa_core.interpreter import RasaNLUHttpInterpreter
from rasa_core.server import create_app
from rasa_core.run import create_argument_parser
from gevent.pywsgi import WSGIServer
from rasa_core.utils import EndpointConfig

logger = logging.getLogger(__name__)

if __name__ == '__main__':
    # Script to run Rasa NLU HTTP Interpreter
    arg_parser = create_argument_parser()
    cmdline_args = arg_parser.parse_args()

    logging.basicConfig(level=cmdline_args.loglevel)
    if cmdline_args.nlu == 'RasaNLUHttpInterpreter':
        logger.info("Creating RasaNLU HTTP Interpreter")
        endpoint = EndpointConfig(os.environ.get("rasa_nlu_http_server"))
        #Fill in the modelname and server details.
        cmdline_args.nlu = RasaNLUHttpInterpreter(os.environ.get("rasa_nlu_model_name"),
                                                endpoint,os.environ.get("rasa_nlu_project_name"))

    app = create_app(cmdline_args.core,
                 cmdline_args.nlu,
                 cmdline_args.loglevel,
                 cmdline_args.log_file,
                 cmdline_args.cors)
    logger.info("Started http server on port %s" % cmdline_args.port)

     # Running the server at 'this' address with the
    # rasa_core application framework
    http_server = WSGIServer(('0.0.0.0', cmdline_args.port), app)
    logger.info("Up and running")
    try:
        http_server.serve_forever()
    except Exception as exc:
        logger.exception(exc)

**Comment by TaraRavindra** [comment]
> Hi,
> I am using RASA_NLU version: 0.14.0a1
> 
> config file:
> 
> pipeline:
> 
> * name: "nlp_spacy"
> * name: "tokenizer_spacy"
> * name: "ner_duckling_http"
>   url: "http://localhost:8000"
>   dimensions: ["time", "phone-number", "url", "email"]
> * name: "ner_crf"
> * name: "ner_synonyms"
> * name: "intent_featurizer_count_vectors"
> * name: "intent_classifier_tensorflow_embedding"
>   intent_tokenization_flag: true
>   intent_split_symbol: ","
> 
> I am running RASA_NLU server:
> python -m rasa_nlu.server -c config/config_file.yml --path /models_storing_path/
> 
> <class 'rasa_nlu.train.TrainingException'>: <TrainingException instance at 0x7fa6ea462ee8 with str error:
> 2018-12-30 10:30:07+0530 [-] Traceback (most recent call last):
> 2018-12-30 10:30:07+0530 [-] File "/home/anaconda3/lib/python3.6/site-packages/twisted/python/reflect.py", line 448, in safe_str
> 2018-12-30 10:30:07+0530 [-] return str(o)
> 2018-12-30 10:30:07+0530 [-] TypeError: **str** returned non-string (type int)
> 2018-12-30 10:30:07+0530 [-] >
> 2018-12-30 10:30:07+0530 [-] ]
> 2018-12-30 10:30:07+0530 [-] Unhandled Error
> Traceback (most recent call last):
> File "/home/anaconda3/lib/python3.6/site-packages/twisted/internet/defer.py", line 501, in errback
> self._startRunCallbacks(fail)
> File "/home/anaconda3/lib/python3.6/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
> self._runCallbacks()
> File "/home/anaconda3/lib/python3.6/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
> current.result = callback(current.result, *args, **kw)
> File "/home/anaconda3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1475, in gotResult
> _inlineCallbacks(r, g, status)
> --- ---
> File "/home/anaconda3/lib/python3.6/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
> result = result.throwExceptionIntoGenerator(g)
> File "/home/anaconda3/lib/python3.6/site-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator
> return g.throw(self.type, self.value, self.tb)
> File "/home/rasa_nlu/rasa_nlu/server.py", line 360, in train
> returnValue(json_to_string({"error": "{}".format(e)}))
> builtins.TypeError: **str** returned non-string (type int)
> 
> 2018-12-30 10:30:07+0530 [-] "127.0.0.1" - - [30/Dec/2018:05:00:07 +0000] "POST /train?project=tester&model=test HTTP/1.1" 500 3798 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
> 2018-12-30 10:31:07+0530 [-] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=52292)
> 
> I dont understand what is the issue "rasa_nlu.train.TrainingException" and
> --> File "/home/rasa_nlu/rasa_nlu/server.py", line 360, in train
> returnValue(json_to_string({"error": "{}".format(e)}))
> builtins.TypeError: **str** returned non-string (type int)
> 
> but when I run docker server it is working and model is built.
> Can someone help me with this.

I am facing same error, any help on this?
