### ISSUE TITLE
Rasa Core Config files empty

### ISSUE THREAD

**Issue by karthikbalu** [paschmann/rasa-ui#63]
I enabled rasa core and added many stories but in the training tab, all the fields are empty
_domain.yml
_stories.md

above are empty 

Please help thanks

**Comment by pradeepmvn** [comment]
Can you please test with the latest master. I fixed the issue by removing the dependency on Entities. Closing this.

**Comment by karthikbalu** [comment]
It worked now :)

What was the challenge running the Rasa core python script internally?

thanks

**Comment by pradeepmvn** [comment]
Rasa Core doesn't have a Train endpoint exposed yet. So there is a manual step involved to export the config files and run the server on a separate machine.

**Comment by karthikbalu** [comment]
How about running the same script you are displaying, command line behind rasa-ui instead of asking the user to run it manually, also both rasa core and rasa nlu can be start stopped from rasa-ui itself

bcs the point of rasa ui is to avoid manual entries and make life easier right, this will drasttically improve the usability

**Comment by paschmann** [comment]
Hi @karthikbalu - Rasa UI requires a HTTP endpoint for running tasks/services against Rasa NLU (like training), but Rasa Core does not have these yet. As soon as it does, we can add the ability to execute this from Rasa UI.

**Comment by tmbo** [comment]
@paschmann is there an issue for this on the Rasa Core repo?

**Comment by paschmann** [comment]
@tmbo - https://github.com/RasaHQ/rasa_core/issues/422

**Comment by srinisubramanian** [comment]
According to https://forum.rasa.com/t/tutorial-required-for-rasa-core-0-11-1-custom-actions-online-training-and-nlg/795 looks like HTTP API for online training is now available.  Any ideas @paschmann if that will help and an ETA on its arrival in the rasa-ui?
