### ISSUE TITLE
Add support for importing/exporting training data

### ISSUE THREAD

**Issue by paschmann** [paschmann/rasa-ui#7]
- Should be able to setup a new system and import back an existing data set

**Comment by NagarajGond** [comment]
@paschmann This is what I requested earlier so that existing RASA user can import the  training data (JSON file) and start using this UI.

**Comment by pradeepmvn** [comment]
This is delivered part of 1.0 #19 
On the Agents page, there will be an import agent button to upload a rasa format json file and train it. Closing this for now.
