### ISSUE TITLE
Make Postgres more configurable

### ISSUE THREAD

**Issue by nac2791** [paschmann/rasa-ui#72]
I would like to run Postgres as a side car container next to the Rasa-ui docker container. The implementation of adding the connection string to the package.json seems unsafe. This would imply I am storing my credentials in plain text. 

Is there anyway to get the connection string to be a runtime variable on the container. Like `POSTGRES_CONNECTION_STRING` or even break it out `POSTGRES_USER`, `POSTGRES_PASSWORD`, etc...

**Comment by pradeepmvn** [comment]
@nac2791 It is already part of an environment variable. All the values available in package.json can be overwritten with environment variables with in a continer. Readme has some info about docker. Below is a sample docker command.

```
docker run -e "rasanluendpoint=http://youripaddress:5000" -e "rasacoreendpoint=http://youripaddress:5005" -e "postgresserver= postgres://postgres:rasaui@localhost:5432/rasaui" -itd -p 5001:5001 rasa-ui
```
