### ISSUE TITLE
Configure corporate proxy to use application

### ISSUE THREAD

**Issue by kumarvgit** [paschmann/rasa-ui#74]
Hello paschmann,

on running command from postgress curl -X GET http://x.x.x.x:5000/status
response returned is: "status": "ready" but on running "**npm start**" from rasaui folder

Rasa Core Error: Error: getaddrinfo ENOTFOUND xxxx xxxx:80
Using connection string from: package.json

Rasa NLU Error: Error: getaddrinfo ENOTFOUND xxxx xxxx:80
Using connection string from: package.json

i am pretty much sure that there is some issue in proxy setting... but how i am not aware.

Thanks in advance.

**Comment by pradeepmvn** [comment]
@kumarvgit Hopefully its resolved. Closing it for now.
