### ISSUE TITLE
unable to resolve entities in training data through rasa-ui

### ISSUE THREAD

**Issue by saurabhzuve** [paschmann/rasa-ui#75]
First of all thanks for creating this tool.
I created an agent and then a few entities and intents within the agent tab.
The problem is that I am unable to add entities in the intents training samples. like in rasa nlu markdown format we can add entities like:
hello [kitty](cat)
I tried using the drop down against the training samples but it shows nothing.

According to the screenshot that you have shared there must be resolved values for the intent expressions. But this behavior is not happening in my case. 
Please help.

**Comment by saurabhzuve** [comment]
hey I got it.
I had to select the entity and click the linking button
i think if there is a tutorial on how to use rasa-ui it would be fantastic!

**Comment by paschmann** [comment]
Good idea @saurabhzuve
