### ISSUE TITLE
UI/UX - use tooltip when classifying intent user expression

### ISSUE THREAD

**Issue by ayashjorden** [paschmann/rasa-ui#77]
Current classification/tagging flow is (IMHO) somewhat cumbersome:
![image](https://user-images.githubusercontent.com/4204371/40566212-53e93f5c-6078-11e8-8870-13e13974c203.png)

1. The user (me) types in the expression
2. mark a word (or several words)
3. Click the _link_ button
4. Click the down-arrow toggle to unfold the entity selection

I'd like to suggest the following flow:
1. The user types in the expression
2. The user marks a word (or several)
3. A **tool-tip** opens up with a dropdown list of entities (auto-complete free text is a plus)
4. The user selects the relevant entity (or clicks a X button to cancel the mark
5. The tool-tip closes on selection

- When the user hovers over a marked word, the bubble opens up with the entity
  - The bubble closes when the mouse hovers-out of the word
  - The bubble has a X button to remove the entity from the word

This should allow removing the _link_ and _down-arrow_ buttons

Appreciate comments,
Yarden

**Comment by pradeepmvn** [comment]
@ayashjorden Awesome feedback. Yes, I have that as a TODO. #57 also referred to the similar changes.
