### ISSUE TITLE
rasa-ui builtin docker container does not work

### ISSUE THREAD

**Issue by reza-ebrahimi** [paschmann/rasa-ui#79]
I have using builtin docker container and cannot login with `admin:admin` username and password, also when I `curl` it, it will returns with an error:

`{"success":false,"message":"No Authorization header."}`

p.s. I have build `docker` image from `master` branch.

**Comment by yuxuan2015** [comment]
@reza-ebrahimi Has your problem been solved?

**Comment by yuxuan2015** [comment]
@reza-ebrahimi https://github.com/paschmann/rasa-ui/issues/78

**Comment by pradeepmvn** [comment]
Please try with the latest image. Closing this for now. Reopen another issue if this is still present.
