### ISSUE TITLE
Current Rasa version is 0.12.3 but Readme says it supports 8.2.?+

### ISSUE THREAD

**Issue by AntonyBaasan** [paschmann/rasa-ui#80]
Why is the required version of Rasa `Version 8.2.?+` on the Readme?
What version of Rasa NLU does this project support (from https://github.com/RasaHQ/rasa_nlu/releases list)?

**Comment by pradeepmvn** [comment]
@AntonyBaasan Thanks for pointing out. That must have been a typo. Updated Readme to reflect latest changes.
