### ISSUE TITLE
Rasa Core via docker

### ISSUE THREAD

**Issue by jlkalberer** [paschmann/rasa-ui#84]
Hi, I'm pretty new to all of this so this might be a dumb question...

I think I got rasa-ui to work with rasa-nlu via the docker container.

Is there a reason that there isn't a public docker file for rasa core? 
Every example I see needs you to build it yourself and pass in a path to some models. Is this a spacy model?

If anyone has an example docker compose file that handles all this setup, that would help a lot.

Thanks!

**Comment by jlkalberer** [comment]
Doh.. I didn't see the official docker file for rasa core

**Comment by pradeepmvn** [comment]
@jlkalberer 

> Every example I see needs you to build it yourself and pass in a path to some models. Is this a spacy model?

RasaCore is a stateful container. So it needs training data and model to be created before starting server. Rasa UI has some instruction on how to start the rasa core as a python process in Training page.
