### ISSUE TITLE
No provision for assigning values for categorical entity types

### ISSUE THREAD

**Issue by anupam20sep** [paschmann/rasa-ui#86]
Using Version 2.1.
When entity is defined as categorical, Shouldn't it  ask for all possible values to be used by an entity type.
When domain.yml file is populated, it shows entity type as categorical with no possible values. 
Rasa core training is completed without any errors ofcourse, but stories doesn't follow the required path.
Same goes with Boolean entity types

**Comment by anupam20sep** [comment]
Thanks @pradeepmvn . Will it be available in next release? However, I my team has already started working on this.

**Comment by pradeepmvn** [comment]
@anupam20sep Will be glad to accept a PR if you still have it. :)
