### ISSUE TITLE
Agent Specific Configs

### ISSUE THREAD

**Issue by ramgesg** [paschmann/rasa-ui#87]
With the current version of RASA NLU, Project specific configuration can be provided. Any plans of adding it here too?

language: "en"

pipeline: "spacy_sklearn"

# data contains the same json, as described in the training data section
data: {
  "rasa_nlu_data": {
    "common_examples": [
      {
        "text": "hey",
        "intent": "greet",
        "entities": []
      }
    ]
  }
}

**Comment by beevelop** [comment]
What's the status of this proposal? Would be quite useful to maintain multiple languages with the same Rasa instance.

**Comment by pradeepmvn** [comment]
@ramgesg They bot are now part of Agent config with the latest Master
