### ISSUE TITLE
I can't train using rasa-ui docker image

### ISSUE THREAD

**Issue by rogerscristo** [paschmann/rasa-ui#89]
I've tried to setup some entities and intentions and then I tried to train, but nothing happens. The "TRAINING JOBS RUNNING" label in Dashboard does not show anything.

I'm using https://hub.docker.com/r/paschmann/rasa-ui/
Running locally with `docker run -itd -p 5001:5001 paschmann/rasa-ui`.

Am I missing something?

Thank you in advance!

**Comment by pradeepmvn** [comment]
@rogerscristo Closing this please open another one if it still persists.
