### ISSUE TITLE
Rasa NLU Error: Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by Haythamamin** [paschmann/rasa-ui#90]
I followed the installation instruction and hen I get to npm start I get the following error:
```
hamin101@ubuntu:~/rasaui$ sudo npm start

> RasaUI@0.2.0 start /home/hamin101/rasaui
> node server/server.js

Rasa UI Server: http://localhost:5001

Express server listening on port 5001

Rasa NLU Error: Error: connect ECONNREFUSED 192.168.186.135:5000
Using connection string from: package.json


Rasa Core Error: Error: connect ECONNREFUSED 192.168.186.135:5005
Using connection string from: package.json


Postgres DB Connected
Using connection string from: package.json
Postgres Server: 127.0.0.1:5432
Database:rasa
Schema:public
```
What am I missing?

**Comment by Haythamamin** [comment]
OK! I get it now Rasa_NLU and Rasa_Core have to be started as well. What is the best way to demonize this whole thing? Is it possible to share approaches and configurations? Would Supervisord do the trick?

**Comment by pradeepmvn** [comment]
@Haythamamin I have another repo where i docker-ized the "whole thing" :) Rasa Stack. Feel free to check it out.
It has a sample Weather Bot and all the data that needs. All you have to do is up the containers.
https://github.com/pradeepmvn/rasa_stack_quickstart
