### ISSUE TITLE
Use existing model and import into Rasa UI

### ISSUE THREAD

**Issue by plambe8** [paschmann/rasa-ui#91]
Hello, I am trying to use Rasa UI with an existing model that I have (locally on my computer). I am confused on how to go about this. The furthest I've gotten is running my model as a server, configuring my package.json, and running npm start. In terminal I get this response:

```
LAMU02W12A4HTD6:resources plambe$ npm start

> RasaUI@0.2.0 start /Users/plambe/Desktop/RepoClones/rasa-ui
> node server/server.js

Rasa UI Server: http://localhost:5001

Express server listening on port 5001

Rasa NLU Connected
Using connection string from: package.json
Rasa NLU Server: http://localhost:5000


Rasa Core Connected
Using connection string from: package.json
Rasa Core Server: http://localhost:5000


Postgres DB Connected
Using connection string from: package.json
Postgres Server: 127.0.0.1:5432
Database:postgres
Schema:public
```

But when open Rasa-UI, my model is not there. I am clearly missing something key here. Can someone assist me?

**Comment by pradeepmvn** [comment]
@plambe8 You should be able to see that new model in the side panel chat box dropdown. But for it to work from rasa-ui, you need to create an Agent with the same name(as Project name) and can test it.
