### ISSUE TITLE
What file to import

### ISSUE THREAD

**Issue by yuxuan2015** [paschmann/rasa-ui#92]
![h6 hj a5 c8cg xub 8u](https://user-images.githubusercontent.com/15645056/42608580-f31c049e-85ba-11e8-8bc5-b03047f638ce.png)

**Comment by haibinzero** [comment]
You can import a json file with the data format defined by rasa_nlu. 
Please import the examples in rasa_nlu to have a try.

**Comment by haibinzero** [comment]
But sames the training out put json will miss the entity values and change it to a null value.
Don't know if it's effect by rasa_nlu version.

**Comment by pradeepmvn** [comment]
@yuxuan2015 you can import an existing rasa_nlu training dataset and give it an Agent name.
