### ISSUE TITLE
No entities created after importing agent

### ISSUE THREAD

**Issue by haibinzero** [paschmann/rasa-ui#93]
I have imported the agent with the examples in the latest rasa_nlu version. There has no entities created in the agent. And in the training page the entity values were null.

**Comment by haibinzero** [comment]
@pradeepmvn can you help? I see there already has code to get entities from the importing file. But no entities in DB after importing.

**Comment by glacierck** [comment]
@haibinzero look！！！！server/db/agents.js
![image](https://user-images.githubusercontent.com/21599896/42920347-c0077fa0-8b48-11e8-8086-98a8f0d8b469.png)

lost the  ‘agent_id’

**Comment by haibinzero** [comment]
Thanks a lot @glacierck , the sql execution failed. 
ERROR:  null value in column "agent_id" violates not-null constraint
DETAIL:  Failing row contains (6, 123, null, NOT_USED).

**Comment by shibei00** [comment]
How to solve it?

**Comment by haibinzero** [comment]
You need to change the agent importing code as glacierck shows.
First move the entity inserting after agent inserting, and add the agent_id into the sql.

**Comment by pradeepmvn** [comment]
@haibinzero initially entites were standalone. But with rasa core support, entities are tied to agent. I will update the code to import after the agent is created !!
