### ISSUE TITLE
unable to display options

### ISSUE THREAD

**Issue by smartinsightsfromdata** [paschmann/rasa-ui#96]
I'm using rasa-ui in the context of this project https://github.com/pradeepmvn/rasa_stack_quickstart

Everything seems to work fine and looking very promising, but:

- When the bot asks "feel free to try these options" nothing appears
- struggles to identify the buttons in the upper right corner in chrome (okeish in safari)

**Comment by pradeepmvn** [comment]
Closing this here. Will keep it active in the other repo. Can you please respond there..
