### ISSUE TITLE
 Failed to connect to localhost port 5000: Connection refused

### ISSUE THREAD

**Issue by bloodraven66** [paschmann/rasa-ui#98]
I'm installing Rasa UI through terminal on ubuntu 16.04. Rasa NLU works properly through HTTP request.
but when I try the below command to validate my Rasa NLU installation before installing rasa UI, I get the following error
curl -X GET http://localhost:5000/status
curl: (7) Failed to connect to localhost port 5000: Connection refused
Anyway I can overcome this without using docker?

**Comment by pradeepmvn** [comment]
@bloodraven66 this docker file will not install rasa_nlu component. It will only install rasa-ui and postgres. 
``Rasa NLU works properly through HTTP request.``
``curl -X GET http://localhost:5000/status``
they both should work. 5000 is for rasa_nlu and rasa-ui uses 5001 port.
