### ISSUE TITLE
Error in editing and trainning entity

### ISSUE THREAD

**Issue by cypoon** [paschmann/rasa-ui#99]
I am installing rasa-ui in window 10 and open in chrome browser. However, it is not able to click the expand entity button in the intent detail page. Moreover, it can not train the entity in the model ! How to overcome this ?

**Comment by pradeepmvn** [comment]
@cypoon  `click the expand entity button in the intent detail page` : Did you select a word for entitiy and click the link icon first? Then the expand button will work.

`it can not train the entity in the model` Can you specify what error you get either in rasa-ui console of rasa_nlu?

**Comment by cypoon** [comment]
I have input the entity in the Entities tab inside Agent. However, those entities cannot be shown in the training json !

**Comment by pradeepmvn** [comment]
`I have input the entity in the Entities tab inside Agent. However, those entities cannot be shown in the training json !`
You should see the list of entities for specific utterences only. Can you check that in the generated json file on the training page?
